negatome('TIFAB', 'TRAF6').
negatome('SAR1A', 'SMAD1').
negatome('KIF5B', 'KIFBP').
negatome('CD93', 'C1QA').
negatome('TSC22D3', 'FOXO3').
negatome('AFDN', 'TERF2IP').
negatome('TAOK1', 'BUB1B').
negatome('BAK1', 'VDAC2').
negatome('EP300', 'CD44').
negatome('C4BPA', 'CD40').
negatome('RNF135', 'MAVS').
negatome('DDX58', 'TRIM25').
negatome('RNF135', 'IFIH1').
negatome('ATP8B3', 'TMEM30B').
negatome('ATP8B4', 'TMEM30B').
negatome('ATP8A1', 'TMEM30B').
negatome('ATP8A2', 'TMEM30B').
negatome('PKN1', 'RPS6KA1').
negatome('PKN2', 'RPS6KA1').
negatome('PKN2', 'RPS6KA3').
negatome('PKN1', 'RPS6KA3').
negatome('POP1', 'NLRP3').
negatome('NR5A2', 'SIRT1').
negatome('FANCA', 'FANCC').
negatome('KDR', 'FLT1').
negatome('IL22', 'IL10RA').
negatome('HIC1', 'SMARCA2').
negatome('STIM1', 'TRPC3').
negatome('STIM1', 'TRPC6').
negatome('BCL10', 'BIRC3').
negatome('VRK2', 'DUSP3').
negatome('SDC2', 'FGF1').
negatome('GPX1', 'ALOX5').
negatome('PARD3', 'LIMK1').
negatome('VRK1', 'RCC1').
negatome('AKAP8L', 'PRKAR2A').
negatome('AKAP8L', 'AKAP8').
negatome('DLK1', 'NOTCH1').
negatome('CDC37L1', 'RAF1').
negatome('POT1', 'TERF2').
negatome('RHOT1', 'KIF5C').
negatome('SMAD1', 'ANAPC10').
negatome('SMAD4', 'ANAPC10').
negatome('EAPP', 'E2F4').
negatome('SH3GLB1', 'BAX').
negatome('CA2', 'SLC26A3').
negatome('RAPGEF1', 'CRK').
negatome('RAPGEF1', 'SHPK').
negatome('RAPGEF1', 'GRB2').
negatome('VAV1', 'SHC1').
negatome('VAV1', 'GRB2').
negatome('GATA1', 'PRKCZ').
negatome('SUMO1', 'GSTK1').
negatome('DKK1', 'WNT1').
negatome('SH3KBP1', 'TNFRSF14').
negatome('CDX2', 'TBP').
negatome('TJAP1', 'F11R').
negatome('TJAP1', 'CLDN1').
negatome('TJAP1', 'TJP1').
negatome('HEY2', 'UBXN4').
negatome('UFD1', 'UBXN4').
negatome('CD274', 'CD28').
negatome('CD274', 'CTLA4').
negatome('HDAC3', 'EPAS1').
negatome('APPL1', 'RAB4A').
negatome('APPL1', 'RAB7A').
negatome('APPL1', 'RAB11A').
negatome('APPL2', 'RAB4A').
negatome('APPL2', 'RAB7A').
negatome('APPL2', 'RAB11A').
negatome('HDAC2', 'RELA').
negatome('EXOC1', 'RHOA').
negatome('F5', 'A2M').
negatome('TSC2', 'SKP2').
negatome('TSC1', 'CDKN1B').
negatome('TSC1', 'SKP2').
negatome('ALK', 'PTN').
negatome('ARAF', 'BCL2L1').
negatome('ARAF', 'BCL2').
negatome('HSPB1', 'EIF4B').
negatome('HSPB1', 'EIF3A').
negatome('HSPB1', 'EIF4E').
negatome('HSPB1', 'EIF4A1').
negatome('HSPB1', 'MKNK1').
negatome('PIK3CG', 'PIK3R2').
negatome('PKN1', 'MAP3K2').
negatome('PKN2', 'MAP3K3').
negatome('BCL2L1', 'MAVS').
negatome('OPA1', 'MAVS').
negatome('UTRN', 'MAVS').
negatome('HTT', 'REST').
negatome('HTT', 'RILP').
negatome('GRAP2', 'KHDRBS1').
negatome('GRAP2', 'SOS1').
negatome('GRAP2', 'CBL').
negatome('FADD', 'CASP8').
negatome('NME1', 'MDM2').
negatome('ERBB2', 'PIK3R2').
negatome('FGFR4', 'FGF2').
negatome('FHOD1', 'RHOA').
negatome('FHOD1', 'CDC42').
negatome('FHOD1', 'RAC2').
negatome('FHOD1', 'RAC3').
negatome('VEGFC', 'FLT1').
negatome('SHC1', 'APP').
negatome('RPL34', 'CDK1').
negatome('NR4A1', 'NCOA6').
negatome('PIAS3', 'STAT1').
negatome('NFYA', 'TBP').
negatome('TBP', 'NFYA').
negatome('RNF7', 'CSNK2A1').
negatome('RABEPK', 'RAB7A').
negatome('RABEPK', 'HRAS').
negatome('COL18A1', 'VEGFA').
negatome('SOCS3', 'JAK2').
negatome('SLA', 'TRAT1').
negatome('CBL', 'TRAT1').
negatome('ZAP70', 'TRAT1').
negatome('LAPTM5', 'TRAT1').
negatome('CD247', 'TRAT1').
negatome('PRNP', 'FZR1').
negatome('ADA', 'DPP4').
negatome('NEDD4', 'SNX9').
negatome('CSNK2A1', 'UBTF').
negatome('EIF4E', 'SCPEP1').
negatome('EIF4E', 'AGO2').
negatome('DCTN4', 'ATP7A').
negatome('COMMD1', 'ATOX1').
negatome('COMMD1', 'ATP7A').
negatome('PFN4', 'ACTB').
negatome('MSX2', 'PML').
negatome('MBD2', 'DNMT3L').
negatome('MBD3', 'DNMT3L').
negatome('SLC4A1', 'ANK1').
negatome('RACK1', 'TP53').
negatome('CCR3', 'CCL3').
negatome('CCR3', 'CCL4').
negatome('HSPA4', 'BAX').
negatome('CD74', 'NOTCH1').
negatome('APLP2', 'CD74').
negatome('PARK7', 'PPARGC1A').
negatome('YWHAZ', 'GSK3B').
negatome('YWHAZ', 'MAPT').
negatome('NCK1', 'EGFR').
negatome('RAB3IP', 'SSX1').
negatome('RAB3IP', 'SSX3').
negatome('RAB3IP', 'SSX4').
negatome('SSX2IP', 'SSX1').
negatome('SSX2IP', 'SSX4').
negatome('HDAC2', 'PHC1').
negatome('HDAC2', 'EZH2').
negatome('HDAC2', 'ELAC2').
negatome('HDAC2', 'RING1').
negatome('VIPR2', 'RAMP1').
negatome('VIPR2', 'RAMP2').
negatome('VIPR2', 'RAMP3').
negatome('FOS', 'HOXD12').
negatome('ETS1', 'CREBBP').
negatome('GABPA', 'CREBBP').
negatome('CXCR4', 'CCR5').
negatome('CA1', 'SLC4A1').
negatome('RB1', 'SMAD3').
negatome('RBL2', 'SMAD3').
negatome('HM13', 'CD74').
negatome('HM13', 'SERP1').
negatome('IL4R', 'IL13').
negatome('PIBF1', 'IL4R').
negatome('TAF6', 'TAF7').
negatome('EPHB6', 'EPHA10').
negatome('CR2', 'PIK3R2').
negatome('GNAO1', 'EYA2').
negatome('IGSF1', 'INHA').
negatome('IGSF1', 'INHBB').
negatome('CEP57', 'FGF1').
negatome('SP1', 'ASF1A').
negatome('MYOD1', 'SET').
negatome('NFKB1', 'SET').
negatome('TP53', 'SET').
negatome('CD2', 'CD48').
negatome('CD2', 'CD59').
negatome('EIF3I', 'ACVR2A').
negatome('EIF3I', 'ACVR1').
negatome('EIF3I', 'TGFBR1').
negatome('TRADD', 'TNFRSF10A').
negatome('RIPK1', 'TNFRSF10A').
negatome('TRADD', 'TNFRSF10B').
negatome('RIPK1', 'TNFRSF10B').
negatome('PGM1', 'S100P').
negatome('TRAF6', 'IRF3').
negatome('IGF2', 'IGF1R').
negatome('TFDP1', 'CDK2').
negatome('TFDP1', 'CCNA1').
negatome('LGALS1', 'FLT1').
negatome('LGALS1', 'KDR').
negatome('LGALS1', 'FLT4').
negatome('RAN', 'RUFY3').
negatome('RAB2A', 'RUFY3').
negatome('RAB7A', 'RUFY3').
negatome('RHOD', 'RUFY3').
negatome('KRAS', 'RUFY3').
negatome('TBC1D7', 'TSC2').
negatome('YWHAB', 'TSC1').
negatome('YWHAE', 'TSC1').
negatome('YWHAG', 'TSC1').
negatome('YWHAH', 'TSC1').
negatome('SFN', 'TSC1').
negatome('YWHAZ', 'TSC1').
negatome('DVL1', 'TSC1').
negatome('AKT1', 'TSC1').
negatome('FOXO1', 'TSC1').
negatome('HERC1', 'TSC1').
negatome('CDKN1B', 'TSC1').
negatome('DKK1', 'SOST').
negatome('TNFAIP6', 'BMP3').
negatome('TLE5', 'HDAC1').
negatome('TLE5', 'HDAC3').
negatome('CTNND1', 'IL2').
negatome('IL15', 'IL2RA').
negatome('OAS1', 'MBD1').
negatome('UMOD', 'TNF').
negatome('HIPK2', 'TP53').
negatome('HIPK2', 'MDM2').
negatome('MED28', 'MSN').
negatome('SERPINE1', 'FN1').
negatome('TADA3', 'RARA').
negatome('NOXA1', 'NCF4').
negatome('RAB15', 'RABEP1').
negatome('RAB15', 'RABGEF1').
negatome('PLAUR', 'PLAU').
negatome('PLAUR', 'CD82').
negatome('AKAP17A', 'U2AF1').
negatome('AKAP17A', 'U2AF2').
negatome('DKC1', 'FANCA').
negatome('LRPAP1', 'APP').
negatome('VDR', 'UIMC1').
negatome('PPARG', 'UIMC1').
negatome('RXRA', 'UIMC1').
negatome('NR1H3', 'UIMC1').
negatome('RARG', 'UIMC1').
negatome('RORC', 'UIMC1').
negatome('INTS9', 'CPSF3').
negatome('INTS11', 'CPSF1').
negatome('INTS9', 'CPSF1').
negatome('CSNK2A2', 'PIN1').
negatome('MAD2L2', 'MAD1L1').
negatome('OSMR', 'LIF').
negatome('OSM', 'LIFR').
negatome('VCP', 'CFTR').
negatome('GLMN', 'IGF1R').
negatome('GLMN', 'INSR').
negatome('RACK1', 'GNAI1').
negatome('RACK1', 'GNAS').
negatome('RACK1', 'GNAQ').
negatome('DTNBP1', 'CSNK1A1').
negatome('DTNBP1', 'CSNK1D').
negatome('DTNBP1', 'CSNK1E').
negatome('DBNDD2', 'CSNK1A1').
negatome('PIGF', 'KDR').
negatome('MYB', 'TP53').
negatome('CXCL9', 'ACKR1').
negatome('CXCL10', 'ACKR1').
negatome('CFP', 'CD55').
negatome('EZH2', 'ELAC2').
negatome('EZH2', 'BMI1').
negatome('PRPS1', 'CREBBP').
negatome('TICAM1', 'TLR4').
negatome('VEGFB', 'KDR').
negatome('TRAF6', 'CD40').
negatome('TRAF1', 'CD40').
negatome('TRAF4', 'CD40').
negatome('TRAF5', 'CD40').
negatome('PDGFC', 'FLT1').
negatome('KRT18', 'PLG').
negatome('BMPR1A', 'TGFB1').
negatome('BMPR1A', 'BMP3').
negatome('BMPR1A', 'BMP5').
negatome('BMPR1A', 'BMP6').
negatome('BMPR1B', 'TGFB1').
negatome('BMPR1B', 'BMP5').
negatome('BMPR1B', 'BMP6').
negatome('CTNND1', 'APC').
negatome('CTNND1', 'CTNNA1').
negatome('CDH1', 'CTNNA1').
negatome('CTNND1', 'CTNND1').
negatome('CTNND1', 'CTNNB1').
negatome('CTNND1', 'JUP').
negatome('LTF', 'CD209').
negatome('LALBA', 'CD209').
negatome('LYZ', 'CD209').
negatome('CSN2', 'CD209').
negatome('SLPI', 'CD209').
negatome('MTA1', 'YY1').
negatome('MTA1', 'FKBP3').
negatome('BANF1', 'CRX').
negatome('NR6A1', 'NCOR2').
negatome('NR6A1', 'NRIP1').
negatome('TAF10', 'TBP').
negatome('TAF10', 'TAF1').
negatome('TAF10', 'TAF2').
negatome('TAF10', 'TAF5').
negatome('TAF10', 'TAF6').
negatome('TAF10', 'TAF7').
negatome('TAF10', 'TAF9').
negatome('TAF10', 'TAF11').
negatome('TAF10', 'TAF12').
negatome('PGF', 'KDR').
negatome('CLU', 'EGFR').
negatome('GHRH', 'TRH').
negatome('CD40LG', 'C4BPA').
negatome('C4BPA', 'FAS').
negatome('C4BPA', 'FASLG').
negatome('DEDD2', 'FADD').
negatome('DEDD2', 'CASP8').
negatome('DEDD2', 'CASP10').
negatome('NKAP', 'RIPK1').
negatome('UBE2A', 'FANCL').
negatome('MESD', 'DKK1').
negatome('CD274', 'ICOS').
negatome('TNFRSF13C', 'TNFSF13').
negatome('VWF', 'F8').
negatome('CTNNB1', 'HSP90AA1').
negatome('CTNNB1', 'HSPD1').
negatome('CTNNB1', 'HSPA4').
negatome('CTNNB1', 'HSP90B1').
negatome('CTNNB1', 'DDIT3').
negatome('NACC1', 'ZBTB16').
negatome('SRSF11', 'SNRNP70').
negatome('SRSF11', 'U2AF1L4').
negatome('MAPK8IP3', 'APP').
negatome('ZYX', 'WT1').
negatome('BMPR2', 'BMP2').
negatome('IL1A', 'EGFR').
negatome('TNF', 'EGFR').
negatome('CSF2RA', 'IL3').
negatome('CSF2', 'IL3RA').
negatome('KDR', 'PGF').
negatome('CD3G', 'ZAP70').
negatome('CD3D', 'ZAP70').
negatome('CD3E', 'ZAP70').
negatome('TNFSF13', 'TNFRSF13C').
negatome('CDK1', 'CCNE1').
negatome('GAS1', 'BCL2').
negatome('GAS1', 'BAX').
negatome('GAS1', 'BAD').
negatome('GAS1', 'BID').
negatome('MCM3', 'STAT1').
negatome('ACVR1', 'INHBA').
negatome('ACVR1', 'INHA').
negatome('TTLL5', 'ESR1').
negatome('TTLL5', 'ESR2').
negatome('TTLL5', 'PPARG').
negatome('TTLL5', 'THRB').
negatome('TTLL5', 'RXRA').
negatome('TTLL5', 'RARA').
negatome('CSNK2A1', 'CSNK2A1').
negatome('CSNK2A1', 'CSNK2A2').
negatome('PPP2R1B', 'PPP2R2A').
negatome('PPP2R1B', 'PPP2R5A').
negatome('PPP2R1B', 'PPP2R5B').
negatome('ZMYM2', 'RCOR1').
negatome('KDM1A', 'RCOR1').
negatome('HDAC1', 'RCOR1').
negatome('CXCR4', 'NPY').
negatome('CXCR4', 'CXCL8').
negatome('CXCR4', 'NAP1L1').
negatome('CSF2RB', 'CSF2').
negatome('AZGP1', 'B2M').
negatome('PGF', 'FLT4').
negatome('VEGFB', 'FLT4').
negatome('CSF2', 'CSF2RB').
negatome('WTIP', 'LMX1B').
negatome('CDC7', 'MCM2').
negatome('PEX12', 'PEX12').
negatome('PEX12', 'PEX14').
negatome('PEX12', 'PEX11B').
negatome('PEX12', 'PEX16').
negatome('PEX7', 'PEX7').
negatome('PEX7', 'PEX2').
negatome('GNB5', 'DNAJC14').
negatome('SMAD7', 'CTBP1').
negatome('LSM1', 'LSM7').
negatome('AXIN1', 'PPP2R1A').
negatome('PRPF4', 'USP39').
negatome('PRPF40A', 'CEP126').
negatome('RBBP4', 'NCOR2').
negatome('RBPJ', 'HDAC2').
negatome('ATF3', 'NFKBIA').
negatome('ZNF3', 'CSK').
negatome('MTREX', 'EXOSC3').
negatome('ARL1', 'GCC2').
negatome('EXOSC7', 'EXOSC7').
negatome('PRPF4', 'PPIH').
negatome('TRPC1', 'TRPC4').
negatome('GEMIN5', 'GEMIN7').
negatome('EXOSC9', 'EXOSC7').
negatome('HMG20A', 'RBM7').
negatome('ID3', 'PIP4K2C').
negatome('ORC2', 'ORC3').
negatome('TRAF3IP1', 'TRAF4').
negatome('PDPK1', 'CMC4').
negatome('CCND1', 'ORC3').
negatome('CSK', 'DUSP6').
negatome('CSK', 'NKX2-3').
negatome('PRPF8', 'PRPF8').
negatome('TLE1', 'TBL1Y').
negatome('TRAF3IP1', 'TRAF6').
negatome('HDAC4', 'HDAC10').
negatome('IKZF4', 'SAP30BP').
negatome('DPF2', 'PTP4A1').
negatome('ZNF331', 'SAP30BP').
negatome('PTP4A1', 'PUF60').
negatome('FHL2', 'RND1').
negatome('EXOSC6', 'EXOSC4').
negatome('BCL2', 'OPTN').
negatome('PBX1', 'MYBBP1A').
negatome('SRSF9', 'SRSF7').
negatome('IMMT', 'ZHX1').
negatome('ATF3', 'ATF4').
negatome('PRPF3', 'PRPF6').
negatome('CNOT3', 'PIP4K2C').
negatome('MTREX', 'EXOSC8').
negatome('PTP4A1', 'EPS8L2').
negatome('LMNA', 'HSPB1').
negatome('YWHAQ', 'AKT1').
negatome('GNB2', 'RND1').
negatome('PEX11A', 'PEX2').
negatome('RAB4A', 'TBXA2R').
negatome('MSN', 'WASF1').
negatome('DPF2', 'IKZF4').
negatome('GDI1', 'DPF2').
negatome('EXOSC4', 'EXOSC4').
negatome('PRPF6', 'PRPF8').
negatome('LSM6', 'LSM4').
negatome('FHL2', 'PIP4K2C').
negatome('NKX2-3', 'NKX2-3').
negatome('ZNF626', 'RND1').
negatome('CRY1', 'FBXO22').
negatome('IKZF4', 'IKZF4').
negatome('XRCC2', 'FANCD2').
negatome('TBL1X', 'TLE1').
negatome('NFKBIA', 'NKX2-3').
negatome('EXOSC9', 'EXOSC2').
negatome('PTN', 'SUMO3').
negatome('CCND1', 'MCM2').
negatome('ARMCX2', 'MAGEH1').
negatome('DGCR8', 'XPO5').
negatome('ZNF331', 'MLX').
negatome('LSM3', 'LSM4').
negatome('GDI1', 'CSK').
negatome('DUSP6', 'SAP30BP').
negatome('VCL', 'PARVB').
negatome('GDI1', 'CREB3L2').
negatome('EXOSC2', 'EXOSC4').
negatome('CREB3L2', 'PUF60').
negatome('EXOSC8', 'DIS3').
negatome('CREB3L2', 'EPS8L2').
negatome('IGF1R', 'ANXA6').
negatome('HOXC8', 'SMAD3').
negatome('APLP1', 'APLP1').
negatome('GNB2', 'DPF2').
negatome('PRPF31', 'PRPF31').
negatome('EXOSC1', 'EXOSC1').
negatome('ZNF331', 'PUF60').
negatome('PEX3', 'PEX3').
negatome('DIS3', 'DIS3').
negatome('BUB1B', 'IL3').
negatome('GDI1', 'ID3').
negatome('RBPJ', 'RBBP8').
negatome('PIP4K2C', 'EPS8L2').
negatome('ATF3', 'NKX2-3').
negatome('NFKBIA', 'CREB3L2').
negatome('ZNF626', 'CREB3L2').
negatome('RND1', 'RND1').
negatome('SART1', 'EFTUD2').
negatome('CNOT3', 'GNL1').
negatome('RB1', 'NLRP2').
negatome('ATF3', 'ZNF408').
negatome('CREB3L2', 'MLX').
negatome('LSM2', 'LSM5').
negatome('FHL2', 'MLX').
negatome('EXOSC2', 'EXOSC3').
negatome('GEMIN2', 'GEMIN5').
negatome('AXIN1', 'SMAD1').
negatome('NEFL', 'PTN').
negatome('ATF3', 'DPF2').
negatome('MAPK3', 'SYT4').
negatome('ID3', 'NKX2-3').
negatome('CHD3', 'ARMCX2').
negatome('CSK', 'PTP4A1').
negatome('CRY2', 'FBXO5').
negatome('SMN1', 'GEMIN5').
negatome('ZNF626', 'PUF60').
negatome('LRIF1', 'ARMCX2').
negatome('FHL1', 'FHL5').
negatome('GDI1', 'PTP4A1').
negatome('TGFBR3', 'ZYX').
negatome('DAZAP2', 'RBPMS').
negatome('PRKN', 'HDAC4').
negatome('CNOT3', 'RND1').
negatome('PRPF40A', 'ARMCX2').
negatome('PTN', 'ZHX1').
negatome('MTREX', 'EXOSC10').
negatome('SNCA', 'SLC1A2').
negatome('RBL2', 'SMAD2').
negatome('ZNF626', 'SAP30BP').
negatome('FOS', 'TAF1').
negatome('TP53', 'NME5').
negatome('CNOT3', 'ZNF331').
negatome('NR3C1', 'FBL').
negatome('EXOSC9', 'EXOSC3').
negatome('COG1', 'COG5').
negatome('NKX2-3', 'MLX').
negatome('PRPF40A', 'NEFL').
negatome('TRIP13', 'C11orf54').
negatome('LRIF1', 'LRIF1').
negatome('EPS8L2', 'ZNF331').
negatome('LSM8', 'LSM7').
negatome('EXOSC8', 'EXOSC3').
negatome('MAGEH1', 'CEP126').
negatome('EEF1G', 'LRIF1').
negatome('ATF3', 'RND1').
negatome('DPF2', 'ZNF408').
negatome('PRPF4', 'TXNL4A').
negatome('EXOSC10', 'EXOSC5').
negatome('ZNF3', 'PTP4A1').
negatome('PTN', 'PTN').
negatome('EXOSC9', 'DIS3').
negatome('E2F3', 'GABPB2').
negatome('PPIH', 'PRPF6').
negatome('SMAD6', 'TRIM33').
negatome('PEX10', 'PEX3').
negatome('CNOT3', 'ZNF3').
negatome('CNOT3', 'GDI1').
negatome('AHSG', 'CAPN6').
negatome('NFKBIA', 'PTP4A1').
negatome('GNB2', 'CREB3L2').
negatome('E2F5', 'GABPB2').
negatome('DPF2', 'PUF60').
negatome('ZNF3', 'NFKBIA').
negatome('MAPK14', 'MKNK2').
negatome('SNRNP70', 'SRSF2').
negatome('ZNF3', 'EPS8L2').
negatome('ATF3', 'CSK').
negatome('EXOSC7', 'EXOSC5').
negatome('PEX16', 'PEX16').
negatome('ZNF3', 'IKZF4').
negatome('THRB', 'PROX1').
negatome('CRY1', 'FBXL15').
negatome('RARA', 'PROX1').
negatome('NFKBIA', 'DPF2').
negatome('APLP1', 'ARMCX2').
negatome('GNB2', 'SAP30BP').
negatome('TRIP13', 'HDHD3').
negatome('CREB3L2', 'PIP4K2C').
negatome('TRIM27', 'PRKACA').
negatome('PPP2CA', 'AP3S1').
negatome('EXOSC9', 'EXOSC4').
negatome('LSM1', 'LSM1').
negatome('LSM1', 'LSM5').
negatome('DNAJB6', 'KRT14').
negatome('PEX11B', 'PEX3').
negatome('PRL', 'PPIA').
negatome('GNL1', 'MLX').
negatome('CRY2', 'BTRC').
negatome('PIP4K2C', 'PUF60').
negatome('EIF4EBP1', 'CHTF18').
negatome('DNAJB6', 'KRT8').
negatome('NEFL', 'ARMCX2').
negatome('TIE1', 'ANGPTL3').
negatome('EXOSC3', 'EXOSC1').
negatome('SNRNP200', 'TXNL4A').
negatome('SMN1', 'GEMIN6').
negatome('SRSF2', 'AKAP17A').
negatome('CSK', 'PIP4K2C').
negatome('MCM2', 'MCM6').
negatome('TRIM16', 'PYCARD').
negatome('CRY1', 'KDM2B').
negatome('LRRFIP1', 'LEF1').
negatome('RND1', 'PUF60').
negatome('CNOT3', 'ZNF212').
negatome('ZNF3', 'SAP30BP').
negatome('GNB2', 'EPS8L2').
negatome('EP300', 'MAFA').
negatome('ZNF626', 'ZNF331').
negatome('COG8', 'COG4').
negatome('GDI1', 'ZNF408').
negatome('EPS8L2', 'ZNF212').
negatome('TUBB', 'TLE1').
negatome('ATF4', 'PIP4K2C').
negatome('EEF1G', 'APLP1').
negatome('MCM2', 'MCM2').
negatome('EXOSC2', 'DIS3').
negatome('ATF3', 'GNB2').
negatome('CRY1', 'FBXO9').
negatome('CYTH3', 'RARA').
negatome('DMC1', 'FANCD2').
negatome('TERF2', 'ACD').
negatome('PIAS4', 'CEP126').
negatome('DRD4', 'KLHL12').
negatome('GNB2', 'ZNF212').
negatome('E2F4', 'GABPB2').
negatome('PRPF8', 'DDX23').
negatome('SMAD7', 'TRIM33').
negatome('FOS', 'MCM2').
negatome('XRCC6', 'H2AX').
negatome('MPHOSPH6', 'DIS3').
negatome('LSM2', 'LSM4').
negatome('TRAF1', 'BIRC7').
negatome('SMAD1', 'TRIM33').
negatome('SMAD7', 'HOXC8').
negatome('LMNA', 'CAMLG').
negatome('ACTN2', 'ILK').
negatome('ORC3', 'ORC3').
negatome('MAPK8', 'MKNK2').
negatome('TRAF5', 'TRAF3IP1').
negatome('TCERG1', 'LRIF1').
negatome('GDI1', 'DUSP6').
negatome('KCTD4', 'KCTD4').
negatome('EFTUD2', 'EFTUD2').
negatome('EEF1G', 'ARMCX2').
negatome('PRKAG1', 'PRKAB1').
negatome('SMAD3', 'HDAC1').
negatome('NFKBIA', 'NFKBIA').
negatome('BCL2L1', 'MCL1').
negatome('FHL2', 'EPS8L2').
negatome('ATF3', 'ZNF331').
negatome('STAT5A', 'GADD45GIP1').
negatome('NFKBIA', 'ID3').
negatome('THRA', 'PROX1').
negatome('CRLF3', 'EIF3C').
negatome('CCL22', 'CCR4').
negatome('SMAD7', 'HOXA9').
negatome('PRPF3', 'SNRNP200').
negatome('PEX14', 'PEX11B').
negatome('GNB2', 'ZNF408').
negatome('EXOSC2', 'EXOSC6').
negatome('PEX10', 'PEX13').
negatome('NKX2-3', 'IKZF4').
negatome('LSM1', 'LSM6').
negatome('FHL2', 'NKX2-3').
negatome('PRPF4', 'EFTUD2').
negatome('NOL3', 'U2AF1').
negatome('PRPF40A', 'LRIF1').
negatome('S100A1', 'S100A11').
negatome('AKT1', 'YWHAB').
negatome('DVL1', 'CTNNB1').
negatome('LSM1', 'LSM8').
negatome('PRPF4', 'SNRNP200').
negatome('CCNT2', 'GRN').
negatome('FTH1', 'FXR2').
negatome('ATF4', 'GDI1').
negatome('ATF4', 'DUSP6').
negatome('E2F2', 'GABPB2').
negatome('USP39', 'PRPF8').
negatome('PEX10', 'PEX2').
negatome('ID3', 'PTP4A1').
negatome('DPF2', 'DPF2').
negatome('CREB3L2', 'ZNF331').
negatome('ATF4', 'MLX').
negatome('RND1', 'EPS8L2').
negatome('SART1', 'TXNL4A').
negatome('PRPF6', 'USP39').
negatome('NFKBIA', 'CSK').
negatome('CDC27', 'CDK9').
negatome('YWHAZ', 'ATP2B2').
negatome('XRCC5', 'RECQL').
negatome('CDKN1A', 'MCM2').
negatome('EXOSC9', 'EXOSC6').
negatome('CSK', 'DPF2').
negatome('CEP126', 'ZHX1').
negatome('PEX7', 'PEX10').
negatome('DVL1', 'CSNK1A1').
negatome('TCERG1', 'TCERG1').
negatome('RAD51B', 'XRCC3').
negatome('XRCC3', 'FANCD2').
negatome('PEX10', 'PEX11A').
negatome('TP53', 'NME3').
negatome('ADRB1', 'AKAP5').
negatome('ATF4', 'GNL1').
negatome('ATF4', 'DPF2').
negatome('ATF4', 'PTP4A1').
negatome('CSK', 'EPS8L2').
negatome('PXN', 'PARVB').
negatome('DYNLL1', 'RASGRP2').
negatome('CREB3L2', 'NKX2-3').
negatome('CREB3L2', 'DPF2').
negatome('TANK', 'RBCK1').
negatome('NKX2-3', 'ZNF408').
negatome('GDI1', 'EPS8L2').
negatome('EXOSC9', 'EXOSC8').
negatome('PEX2', 'PEX16').
negatome('SCN1B', 'SCN3B').
negatome('EXOSC4', 'EXOSC3').
negatome('RAD51', 'RAD54B').
negatome('NKX2-3', 'PUF60').
negatome('CREB3L2', 'SAP30BP').
negatome('SLC1A2', 'RRS1').
negatome('DUSP6', 'IKZF4').
negatome('PRPF4', 'SART1').
negatome('MPHOSPH6', 'MPHOSPH6').
negatome('TP53', 'TP63').
negatome('EXOSC7', 'EXOSC3').
negatome('EXOSC9', 'EXOSC1').
negatome('TRAPPC9', 'IKBKG').
negatome('ATF3', 'ZNF626').
negatome('MLH1', 'PMS2').
negatome('CDKN2A', 'ORC3').
negatome('COG1', 'COG6').
negatome('TEK', 'ANGPTL3').
negatome('MTREX', 'EXOSC9').
negatome('RND1', 'MLX').
negatome('PTP4A1', 'ZNF408').
negatome('SMAD4', 'CREBBP').
negatome('EXOSC6', 'MPHOSPH6').
negatome('RYK', 'AFDN').
negatome('ID3', 'IKZF4').
negatome('TERF2', 'POT1').
negatome('TCERG1', 'NEFL').
negatome('ATF4', 'ZNF626').
negatome('GNL1', 'GNB2').
negatome('CHD3', 'MAGEH1').
negatome('EXOSC2', 'EXOSC2').
negatome('SMAD3', 'E2F1').
negatome('NFKBIA', 'ZNF331').
negatome('MCM4', 'ORC3').
negatome('ZBTB8B', 'ZBTB8B').
negatome('USP39', 'PRPF31').
negatome('RAD51C', 'FANCD2').
negatome('ATF4', 'ZNF331').
negatome('NFKBIA', 'GNL1').
negatome('COG2', 'COG5').
negatome('PEX12', 'PEX2').
negatome('PEX12', 'PEX3').
negatome('SIVA1', 'LPAR1').
negatome('DNAJB6', 'DES').
negatome('SAP30', 'RBPJ').
negatome('PEX11B', 'PEX2').
negatome('HRAS', 'MAPK1').
negatome('NFKBIA', 'PUF60').
negatome('EEF1G', 'ZHX1').
negatome('RAD54L', 'FANCD2').
negatome('PEX13', 'PEX16').
negatome('NKX2-3', 'PTP4A1').
negatome('IKZF4', 'MLX').
negatome('ATF3', 'MLX').
negatome('RDX', 'DOCK1').
negatome('ID3', 'CREB3L2').
negatome('CRY1', 'FBXO5').
negatome('NKX2-3', 'PIP4K2C').
negatome('EXOSC7', 'EXOSC4').
negatome('PTPN2', 'YWHAB').
negatome('RACK1', 'PDE4C').
negatome('NKX2-3', 'DPF2').
negatome('RND1', 'PTP4A1').
negatome('COG4', 'COG6').
negatome('EXOSC10', 'EXOSC9').
negatome('ATF4', 'PUF60').
negatome('GNL1', 'CSK').
negatome('APLP1', 'MAGEH1').
negatome('SUMO3', 'MAGEH1').
negatome('GNB2', 'FHL2').
negatome('SKP2', 'CRY2').
negatome('GNL1', 'ZNF408').
negatome('ZNF626', 'EPS8L2').
negatome('PEX7', 'PEX14').
negatome('NCOR1', 'PROX1').
negatome('TACC1', 'KAT2B').
negatome('BCL2', 'MCL1').
negatome('RGS16', 'ADRA1A').
negatome('PTN', 'LRIF1').
negatome('FHL1', 'FHL1').
negatome('PIP4K2C', 'ZNF212').
negatome('DUSP6', 'CREB3L2').
negatome('PRPF3', 'TXNL4A').
negatome('MTREX', 'EXOSC1').
negatome('EXOSC10', 'EXOSC7').
negatome('PCNA', 'CDKN1A').
negatome('TXNL4A', 'TXNL4A').
negatome('FHL1', 'FHL2').
negatome('TCERG1', 'PRPF40A').
negatome('PPIH', 'SNRNP200').
negatome('PEX14', 'PEX16').
negatome('CDC45', 'MCM2').
negatome('NFKBIA', 'ZNF626').
negatome('GNL1', 'NKX2-3').
negatome('GNL1', 'EPS8L2').
negatome('FHL2', 'PTP4A1').
negatome('COG7', 'COG3').
negatome('XIAP', 'TRAF1').
negatome('CSK', 'GNB2').
negatome('GEMIN5', 'GEMIN6').
negatome('STX11', 'FHL3').
negatome('TRAF1', 'TRAF3IP1').
negatome('COG3', 'COG5').
negatome('IKZF4', 'ZNF212').
negatome('MPHOSPH6', 'EXOSC1').
negatome('MAGEH1', 'MAGEH1').
negatome('GATA2', 'TLE1').
negatome('PRPF4', 'DDX23').
negatome('PRPF3', 'PRPF3').
negatome('CNOT3', 'NKX2-3').
negatome('CNOT3', 'MLX').
negatome('NCOR1', 'NR0B2').
negatome('PRPF40A', 'MAGEH1').
negatome('POU1F1', 'TLE1').
negatome('COG2', 'COG1').
negatome('EIF3E', 'CRLF3').
negatome('DNAJC14', 'GNB4').
negatome('ATF4', 'FHL2').
negatome('GDI1', 'FHL2').
negatome('RND1', 'IKZF4').
negatome('DUSP6', 'RND1').
negatome('PIP4K2C', 'IKZF4').
negatome('LSM2', 'LSM2').
negatome('CRY2', 'KDM2A').
negatome('MPHOSPH6', 'EXOSC3').
negatome('RND1', 'ZNF331').
negatome('YWHAQ', 'ATP2B2').
negatome('GNB2', 'MLX').
negatome('EWSR1', 'RAB37').
negatome('EXOSC6', 'EXOSC5').
negatome('PIP4K2C', 'ZNF408').
negatome('ORC1', 'ORC3').
negatome('PEX10', 'PEX10').
negatome('PRPF40A', 'PRPF40A').
negatome('NR0B2', 'PROX1').
negatome('PIP4K2C', 'PTP4A1').
negatome('COG7', 'COG4').
negatome('EFTUD2', 'PRPF31').
negatome('ATF3', 'PIP4K2C').
negatome('GDI1', 'GNB2').
negatome('GNB2', 'IKZF4').
negatome('PEX12', 'PEX13').
negatome('PEX7', 'PEX13').
negatome('PPIH', 'PPIH').
negatome('LSM8', 'LSM8').
negatome('NR3C1', 'PROX1').
negatome('MAPK3', 'DUSP26').
negatome('SLC1A2', 'DDX41').
negatome('PTN', 'EEF1G').
negatome('TOM1L2', 'ZFYVE16').
negatome('ZNF408', 'PUF60').
negatome('ZNF3', 'DUSP6').
negatome('ATF4', 'IKZF4').
negatome('SUMO3', 'LRIF1').
negatome('PRPF8', 'PRPF31').
negatome('RND1', 'SAP30BP').
negatome('NFKBIA', 'GNB2').
negatome('E2F1', 'SMAD2').
negatome('NKX2-3', 'EPS8L2').
negatome('CRY2', 'KDM2B').
negatome('TP53', 'DAXX').
negatome('EXOSC8', 'EXOSC1').
negatome('UBE2B', 'SUMO1').
negatome('FHL2', 'DUSP6').
negatome('PTN', 'MAGEH1').
negatome('MAPK3', 'GLYR1').
negatome('ATF3', 'PUF60').
negatome('STAT6', 'DHX9').
negatome('EEF1G', 'PIAS4').
negatome('GDI1', 'ZNF626').
negatome('EPS8L2', 'SAP30BP').
negatome('MLX', 'MLX').
negatome('AXIN1', 'SMAD4').
negatome('NOL3', 'SRSF3').
negatome('PEX2', 'PEX2').
negatome('GDI1', 'GDI1').
negatome('EWSR1', 'RMND5B').
negatome('SUMO3', 'ARMCX2').
negatome('SKP2', 'CRY1').
negatome('LMNA', 'YWHAB').
negatome('COG2', 'COG6').
negatome('ATF4', 'ATF4').
negatome('GNB1', 'DNAJC14').
negatome('ZHX1', 'ZHX1').
negatome('PPIH', 'DDX23').
negatome('FYN', 'PRKCA').
negatome('TERF1', 'ACD').
negatome('FADD', 'TICAM1').
negatome('FHL2', 'CREB3L2').
negatome('IL4', 'IL13RA1').
negatome('GNL1', 'PUF60').
negatome('PUF60', 'PUF60').
negatome('MCM7', 'ORC3').
negatome('CDK3', 'ORC3').
negatome('CNOT3', 'NFKBIA').
negatome('NEFL', 'SUMO3').
negatome('PEX11A', 'PEX13').
negatome('SAP30', 'PHF12').
negatome('NKX2-3', 'RND1').
negatome('SNRNP200', 'PRPF31').
negatome('EEF1G', 'CEP126').
negatome('PEX11A', 'PEX14').
negatome('TAB1', 'RBCK1').
negatome('LYN', 'PRKCA').
negatome('GNL1', 'IKZF4').
negatome('DVL1', 'GSK3B').
negatome('TCERG1', 'APLP1').
negatome('PROP1', 'TLE1').
negatome('STX11', 'FHL2').
negatome('TUBB', 'PARP1').
negatome('ATF4', 'RND1').
negatome('NQO1', 'MDM2').
negatome('APLP1', 'PIAS4').
negatome('TP73', 'HECW1').
negatome('RB1', 'SIN3A').
negatome('XRCC3', 'RAD51D').
negatome('FLT1', 'ACP1').
negatome('PEX2', 'PEX13').
negatome('MAPK8', 'MKNK1').
negatome('HOXC8', 'SMAD2').
negatome('DUSP6', 'EPS8L2').
negatome('ATF3', 'DUSP6').
negatome('LSM5', 'LSM5').
negatome('TCERG1', 'CEP126').
negatome('NFKBIA', 'SAP30BP').
negatome('CHD3', 'CHD3').
negatome('CSK', 'CREB3L2').
negatome('CHD3', 'CEP126').
negatome('CRY1', 'KDM2A').
negatome('RAD51B', 'FANCD2').
negatome('RAD51', 'FANCD2').
negatome('DUSP6', 'DUSP6').
negatome('EXOSC5', 'EXOSC5').
negatome('SART1', 'PRPF8').
negatome('KRT15', 'LNX1').
negatome('MTREX', 'DIS3').
negatome('RND1', 'ZNF408').
negatome('PROX1', 'NCOR2').
negatome('EPS8L2', 'MLX').
negatome('EXOSC7', 'EXOSC8').
negatome('PTP4A1', 'PTP4A1').
negatome('PRPF3', 'DDX23').
negatome('PEX11B', 'PEX11B').
negatome('NEFL', 'EEF1G').
negatome('EEF1G', 'IMMT').
negatome('ATF4', 'GNB2').
negatome('PRPF3', 'PPIH').
negatome('PEX14', 'PEX3').
negatome('CBX5', 'TRIM28').
negatome('DLG4', 'GRIN1').
negatome('CNOT3', 'ZNF626').
negatome('XRCC6', 'RECQL').
negatome('ATF4', 'ZNF408').
negatome('CBX3', 'TRIM28').
negatome('SMAD4', 'TGIF1').
negatome('PRKG1', 'IRAG1').
negatome('DPF2', 'MLX').
negatome('MTREX', 'MTREX').
negatome('EXOSC3', 'DIS3').
negatome('ZNF3', 'PUF60').
negatome('EXOSC4', 'DIS3').
negatome('UBE2E1', 'SUMO1').
negatome('PIAS4', 'PIAS4').
negatome('CTNND1', 'CTNNAL1').
negatome('CNOT3', 'ATF3').
negatome('GNL1', 'SAP30BP').
negatome('APLP1', 'CHD3').
negatome('CNOT3', 'DPF2').
negatome('EXOSC10', 'EXOSC8').
negatome('SNRNP200', 'DDX23').
negatome('NFKBIA', 'FHL2').
negatome('ZBTB33', 'ZBTB4').
negatome('ZNF212', 'PUF60').
negatome('CNOT3', 'CREB3L2').
negatome('SMAD3', 'TRIM33').
negatome('SNRNP70', 'AKAP17A').
negatome('NEFL', 'CEP126').
negatome('SKI', 'SMAD4').
negatome('ZNF3', 'GNB2').
negatome('E2F1', 'GABPB1').
negatome('LSM7', 'LSM7').
negatome('MCM2', 'ORC1').
negatome('ARMCX2', 'PIAS4').
negatome('ID3', 'ZNF212').
negatome('HDAC1', 'HEY2').
negatome('ZNF3', 'GDI1').
negatome('GDI1', 'ZNF331').
negatome('GNL1', 'ZNF331').
negatome('EXOSC10', 'EXOSC3').
negatome('CRY2', 'FBXO22').
negatome('NKX2-3', 'SAP30BP').
negatome('PIP4K2C', 'RND1').
negatome('TBL1X', 'PARP1').
negatome('PEX11A', 'PEX16').
negatome('LSM8', 'LSM5').
negatome('CCNE2', 'MCM2').
negatome('MCL1', 'BCL2L2').
negatome('YWHAE', 'ATP2B2').
negatome('GDI1', 'SAP30BP').
negatome('E2F1', 'GABPA').
negatome('IKZF4', 'PUF60').
negatome('PEX2', 'PEX3').
negatome('GDI1', 'ZNF212').
negatome('CSK', 'IKZF4').
negatome('NEFL', 'MAGEH1').
negatome('PSEN1', 'PAWR').
negatome('EXOSC9', 'EXOSC5').
negatome('PEX7', 'PEX11A').
negatome('PEX7', 'PEX16').
negatome('CHUK', 'TRAPPC9').
negatome('GPR39', 'GHRL').
negatome('PRPF3', 'PRPF8').
negatome('SNAI2', 'CTBP1').
negatome('TOM1L1', 'ZFYVE16').
negatome('RB1', 'SMAD2').
negatome('AREG', 'NKD2').
negatome('TGFA', 'NKD1').
negatome('ZNF3', 'GNL1').
negatome('DNAJB6', 'VIM').
negatome('GDI1', 'IKZF4').
negatome('DNM2', 'VAV3').
negatome('ID3', 'DPF2').
negatome('IMMT', 'MAGEH1').
negatome('CREB3L2', 'IKZF4').
negatome('NFKBIA', 'ZNF408').
negatome('HIF1A', 'IKBKG').
negatome('PTP4A1', 'MLX').
negatome('ZEB1', 'HDAC1').
negatome('PRPF40A', 'IMMT').
negatome('NFKBIA', 'RND1').
negatome('RAD52', 'FANCD2').
negatome('PRPF3', 'EFTUD2').
negatome('EXOSC9', 'MPHOSPH6').
negatome('LRIF1', 'MAGEH1').
negatome('SUMO3', 'SUMO3').
negatome('ID3', 'SAP30BP').
negatome('GTF2I', 'PRKG1').
negatome('ATF3', 'CREB3L2').
negatome('GDI1', 'MLX').
negatome('EXOSC7', 'MPHOSPH6').
negatome('PEX7', 'PEX11B').
negatome('NEFL', 'ZHX1').
negatome('GNB2', 'PUF60').
negatome('ATF3', 'GNL1').
negatome('PTN', 'CEP126').
negatome('GNL1', 'ZNF626').
negatome('TCERG1', 'ZHX1').
negatome('CNOT3', 'GNB2').
negatome('CNOT3', 'IKZF4').
negatome('RND1', 'DPF2').
negatome('CNOT3', 'FHL2').
negatome('GNB2', 'GNB2').
negatome('EXOSC7', 'EXOSC1').
negatome('CEP126', 'CEP126').
negatome('RIPK2', 'CARD18').
negatome('GNB2', 'NKX2-3').
negatome('ID3', 'ZNF331').
negatome('PEX14', 'PEX2').
negatome('NOL3', 'SRSF4').
negatome('GMNN', 'MCM2').
negatome('ARMCX2', 'ZHX1').
negatome('IMMT', 'CEP126').
negatome('ZNF408', 'MLX').
negatome('COPB2', 'PDE4D').
negatome('DUSP6', 'DPF2').
negatome('RGS16', 'ADRA1D').
negatome('COG7', 'COG2').
negatome('EFTUD2', 'USP39').
negatome('LSM5', 'LSM4').
negatome('ATP2B4', 'YWHAQ').
negatome('DUSP6', 'ZNF626').
negatome('LSM3', 'LSM5').
negatome('EXOSC2', 'MPHOSPH6').
negatome('DCC', 'HJV').
negatome('HDAC1', 'PHF12').
negatome('GDI1', 'PIP4K2C').
negatome('EXOSC8', 'MPHOSPH6').
negatome('RBPJ', 'MAML1').
negatome('DPF2', 'ZNF331').
negatome('RGS16', 'ADRA1B').
negatome('PRPF4', 'PRPF3').
negatome('RIPK2', 'CARD17').
negatome('HRAS', 'MAPK8').
negatome('ZNF3', 'ATF4').
negatome('GDI1', 'PUF60').
negatome('EEF1G', 'CHD3').
negatome('MCM4', 'MCM2').
negatome('SNRNP200', 'SNRNP200').
negatome('HRH1', 'NCDN').
negatome('ZNF3', 'ATF3').
negatome('DUSP6', 'MLX').
negatome('NOL3', 'SRSF1').
negatome('NME6', 'TP53').
negatome('STAT1', 'GADD45GIP1').
negatome('EXOSC10', 'EXOSC10').
negatome('TFDP1', 'GABPB2').
negatome('PDPK1', 'TCL1B').
negatome('PPIH', 'EFTUD2').
negatome('SNRNP200', 'USP39').
negatome('ADRA1D', 'RGS2').
negatome('SUMO3', 'ZHX1').
negatome('ATF4', 'SAP30BP').
negatome('PTP4A1', 'ZNF331').
negatome('NOL3', 'TRA2B').
negatome('CFTR', 'CLCN1').
negatome('ATF3', 'SAP30BP').
negatome('MAPT', 'GSK3B').
negatome('ATF4', 'ID3').
negatome('MTREX', 'EXOSC2').
negatome('ZNF626', 'ZNF408').
negatome('LSM4', 'LSM4').
negatome('PSMC3', 'SNCB').
negatome('ATF3', 'IKZF4').
negatome('ADRA1B', 'RGS2').
negatome('CNOT3', 'ZNF408').
negatome('TXNL4A', 'PRPF8').
negatome('EGFR', 'SH3KBP1').
negatome('CSK', 'ZNF408').
negatome('TERF1', 'TERF2').
negatome('PEX3', 'PEX13').
negatome('PEX11B', 'PEX13').
negatome('CRY1', 'FBXL2').
negatome('PDE4A', 'RACK1').
negatome('LSM6', 'LSM2').
negatome('CSK', 'SAP30BP').
negatome('SMAD4', 'SMURF2').
negatome('EXOSC8', 'EXOSC4').
negatome('PEX12', 'PEX11A').
negatome('PEX7', 'PEX3').
negatome('TCERG1', 'PTN').
negatome('TCERG1', 'EEF1G').
negatome('TCERG1', 'IMMT').
negatome('XRCC3', 'XRCC2').
negatome('FRS3', 'RND3').
negatome('TOM1', 'ZFYVE9').
negatome('NOL3', 'SNRPN').
negatome('NOL3', 'SRSF2').
negatome('NFKBIA', 'GDI1').
negatome('PRPF40A', 'EEF1G').
negatome('EXOSC10', 'EXOSC6').
negatome('ZNF626', 'IKZF4').
negatome('GNL1', 'CREB3L2').
negatome('DCTD', 'LNX1').
negatome('SRSF3', 'AKAP17A').
negatome('EXOSC10', 'EXOSC2').
negatome('EXOSC10', 'DIS3').
negatome('USP39', 'DDX23').
negatome('EPS8L2', 'PUF60').
negatome('PRKCB', 'SRC').
negatome('NEFL', 'APLP1').
negatome('RBL2', 'GABPB2').
negatome('MPHOSPH6', 'EXOSC4').
negatome('ATF3', 'EPS8L2').
negatome('DUSP6', 'PUF60').
negatome('PTP4A1', 'SAP30BP').
negatome('DNAJB6', 'GFAP').
negatome('CSK', 'PUF60').
negatome('CRY2', 'FBXL15').
negatome('MCM2', 'ORC6').
negatome('IMMT', 'ARMCX2').
negatome('NFKBIA', 'DUSP6').
negatome('HOXA9', 'SMAD3').
negatome('DPF2', 'EPS8L2').
negatome('ZNF626', 'MLX').
negatome('MAPK1', 'OSR1').
negatome('DUSP6', 'NKX2-3').
negatome('GDI1', 'NKX2-3').
negatome('EXOSC10', 'EXOSC1').
negatome('ACD', 'TERF2IP').
negatome('EXOSC3', 'EXOSC3').
negatome('RACK1', 'PRKCQ').
negatome('DPF2', 'SAP30BP').
negatome('CDK2', 'MCM2').
negatome('LSM3', 'LSM3').
negatome('SART1', 'PPIH').
negatome('ZNF3', 'MLX').
negatome('ZNF626', 'ZNF212').
negatome('IKZF4', 'ZNF331').
negatome('PRPF3', 'PRPF31').
negatome('ZNF3', 'ZNF408').
negatome('BCAP31', 'BAX').
negatome('ZNF626', 'ZNF626').
negatome('MLX', 'PUF60').
negatome('PRPF40A', 'PTN').
negatome('ZNF3', 'PIP4K2C').
negatome('EXOSC2', 'EXOSC1').
negatome('SMAD2', 'TRIM33').
negatome('ZNF3', 'NKX2-3').
negatome('CRY2', 'FBXL2').
negatome('PIP4K2C', 'DPF2').
negatome('EPS8L2', 'ZNF408').
negatome('TCERG1', 'SUMO3').
negatome('NOL3', 'SAFB').
negatome('CNOT3', 'EPS8L2').
negatome('DNAJB6', 'KRT5').
negatome('PTN', 'ARMCX2').
negatome('CRK', 'SYT4').
negatome('ZNF626', 'PTP4A1').
negatome('RACK1', 'PDE4B').
negatome('PEX11A', 'PEX11B').
negatome('CSK', 'CSK').
negatome('COG7', 'COG1').
negatome('ZNF626', 'NKX2-3').
negatome('PEX11A', 'PEX3').
negatome('MSX1', 'TLE1').
negatome('GNL1', 'DPF2').
negatome('TXNL4A', 'EFTUD2').
negatome('FUBP3', 'PUF60').
negatome('S100A6', 'S100A1').
negatome('ACTN2', 'TRIM54').
negatome('LSM6', 'LSM7').
negatome('PIP4K2C', 'SAP30BP').
negatome('CNOT3', 'PTP4A1').
negatome('EXOSC9', 'EXOSC9').
negatome('GNL1', 'FHL2').
negatome('EXOSC2', 'EXOSC8').
negatome('CNOT3', 'PUF60').
negatome('RAB4A', 'RAB11FIP1').
negatome('SNRNP200', 'PRPF6').
negatome('RAD51D', 'FANCD2').
negatome('GNB2', 'ZNF331').
negatome('SUMO1', 'UBE2S').
negatome('EPS8L2', 'EPS8L2').
negatome('DUSP6', 'PTP4A1').
negatome('PTN', 'IMMT').
negatome('GNB2', 'DNAJC14').
negatome('NFKBIA', 'PIP4K2C').
negatome('CRY2', 'FBXO9').
negatome('C1QBP', 'NFYC').
negatome('CSK', 'MLX').
negatome('PTP4A1', 'IKZF4').
negatome('COG3', 'COG6').
negatome('ZNF212', 'MLX').
negatome('GNB2', 'PTP4A1').
negatome('TCERG1', 'ARMCX2').
negatome('PPIH', 'USP39').
negatome('TRAF2', 'TRAF3IP1').
negatome('ATF3', 'PTP4A1').
negatome('SMAD3', 'RBL2').
negatome('NF2', 'WASF1').
negatome('FXR2', 'RBPMS').
negatome('EXOSC6', 'EXOSC3').
negatome('ATP2B4', 'YWHAZ').
negatome('LSM7', 'LSM2').
negatome('GNL1', 'DUSP6').
negatome('CSK', 'ZNF626').
negatome('MAP4K4', 'RAP1A').
negatome('RXRA', 'PROX1').
negatome('ZNF626', 'PIP4K2C').
negatome('CDK2', 'ORC3').
negatome('HOXA9', 'SMAD2').
negatome('TINF2', 'TERF2IP').
negatome('DUSP6', 'PIP4K2C').
negatome('COG3', 'COG8').
negatome('EFTUD2', 'PRPF8').
negatome('AXIN1', 'SMAD5').
negatome('PPIH', 'PRPF8').
negatome('BRD4', 'PCNA').
negatome('NOL3', 'SRSF6').
negatome('CNOT3', 'DUSP6').
negatome('STX11', 'FHL1').
negatome('PRKCB', 'FYN').
negatome('ZNF3', 'DPF2').
negatome('EXOSC4', 'EXOSC5').
negatome('ATF4', 'CREB3L2').
negatome('GNB2', 'DUSP6').
negatome('EXOSC6', 'EXOSC6').
negatome('PKD2L2', 'CBY1').
negatome('ACP1', 'TIE1').
negatome('EEF1G', 'MAGEH1').
negatome('GNL1', 'GNL1').
negatome('GNL1', 'ID3').
negatome('EXOSC6', 'DIS3').
negatome('NAIP', 'DIABLO').
negatome('CDC5L', 'ORC3').
negatome('ID3', 'EPS8L2').
negatome('TCERG1', 'MAGEH1').
negatome('CNOT3', 'SAP30BP').
negatome('ATF3', 'GDI1').
negatome('LSM6', 'LSM6').
negatome('ZNF3', 'ZNF626').
negatome('ATF4', 'CSK').
negatome('LRIF1', 'ZHX1').
negatome('COG3', 'COG4').
negatome('PRPF4', 'PRPF8').
negatome('NEFL', 'LRIF1').
negatome('RBL1', 'HDAC1').
negatome('DNM2', 'VAV2').
negatome('EXOSC2', 'EXOSC5').
negatome('CTNNA1', 'CTNNAL1').
negatome('APLP1', 'ZHX1').
negatome('PDPK1', 'TCL1A').
negatome('SNRNP200', 'PRPF8').
negatome('SUMO1', 'CHD3').
negatome('EXOSC10', 'EXOSC4').
negatome('PIP4K2C', 'MLX').
negatome('MTREX', 'EXOSC7').
negatome('SMAD3', 'SIN3A').
negatome('HRAS', 'MAPK14').
negatome('SKIL', 'SMURF2').
negatome('EEF1G', 'SUMO3').
negatome('APLP1', 'SUMO3').
negatome('COG2', 'COG8').
negatome('DIS3', 'EXOSC1').
negatome('CTNNB1', 'PPP1CA').
negatome('COG1', 'COG8').
negatome('ORC4', 'MCM2').
negatome('TPM3', 'DSTN').
negatome('GNL1', 'RND1').
negatome('HDAC10', 'HDAC6').
negatome('EXOSC8', 'EXOSC8').
negatome('BRCA2', 'RAD51').
negatome('NR0B1', 'PROX1').
negatome('NFYB', 'NFYC').
negatome('MPHOSPH6', 'EXOSC5').
negatome('MAPK8', 'GLYR1').
negatome('APLP1', 'IMMT').
negatome('CBX1', 'TRIM28').
negatome('CREB3L2', 'ZNF408').
negatome('GNL1', 'PIP4K2C').
negatome('NFKBIA', 'MLX').
negatome('CRY1', 'BTRC').
negatome('POT1', 'TERF2IP').
negatome('ZNF3', 'CREB3L2').
negatome('CSK', 'ZNF331').
negatome('SAP30BP', 'SAP30BP').
negatome('PEX11B', 'PEX16').
negatome('LCK', 'PTPRG').
negatome('RND3', 'FRS2').
negatome('PEX11A', 'PEX11A').
negatome('GNB2', 'ZNF626').
negatome('IKZF4', 'ZNF408').
negatome('SIVA1', 'LPAR3').
negatome('CREB3L2', 'CREB3L2').
negatome('CNOT3', 'CNOT3').
negatome('PBX2', 'MYBBP1A').
negatome('MAGEH1', 'ZHX1').
negatome('EXOSC5', 'DIS3').
negatome('ID3', 'DUSP6').
negatome('ATF4', 'NKX2-3').
negatome('CSK', 'RND1').
negatome('PIP4K2C', 'ZNF331').
negatome('USP39', 'USP39').
negatome('PEX10', 'PEX16').
negatome('CNOT3', 'ATF4').
negatome('SNRNP200', 'EFTUD2').
negatome('ZNF3', 'ZNF331').
negatome('GDI1', 'RND1').
negatome('ZNF626', 'DPF2').
negatome('GNAI1', 'DNAJC14').
negatome('CDK4', 'ORC3').
negatome('GNB3', 'DNAJC14').
negatome('ATF4', 'EPS8L2').
negatome('DUSP6', 'ZNF408').
negatome('ZNF3', 'RND1').
negatome('TXNL4A', 'USP39').
negatome('MTREX', 'EXOSC4').
negatome('RBPJ', 'RING1').
negatome('NFKBIA', 'EPS8L2').
negatome('SUMO3', 'IMMT').
negatome('AHSG', 'CAPN1').
negatome('EXOSC7', 'DIS3').
negatome('NKX2-3', 'ZNF331').
negatome('CNOT3', 'CSK').
negatome('PRPF40A', 'SUMO3').
negatome('GNB2', 'PIP4K2C').
negatome('MTREX', 'EXOSC5').
negatome('PEX3', 'PEX16').
negatome('DUSP6', 'ZNF331').
negatome('NINL', 'MAD1L1').
