enzyme_class('AAK1', kinase, st).
enzyme_class('AATK', kinase, st).
enzyme_class('ABL1', kinase, y).
enzyme_class('ABL2', kinase, y).
enzyme_class('ACVR1', kinase, st).
enzyme_class('ACVR1B', kinase, st).
enzyme_class('ACVR1C', kinase, st).
enzyme_class('ACVR2A', kinase, st).
enzyme_class('ACVR2B', kinase, st).
enzyme_class('ACVRL1', kinase, st).
enzyme_class('ADCK1', kinase, unknown).
enzyme_class('ADCK2', kinase, st).
enzyme_class('ADCK5', kinase, st).
enzyme_class('AKT1', kinase, st).
enzyme_class('AKT2', kinase, st).
enzyme_class('AKT3', kinase, st).
enzyme_class('ALK', kinase, y).
enzyme_class('ALPK1', kinase, st).
enzyme_class('ALPK2', kinase, st).
enzyme_class('ALPK3', kinase, st).
enzyme_class('AMHR2', kinase, st).
enzyme_class('ANKK1', kinase, st).
enzyme_class('ARAF', kinase, st).
enzyme_class('ATM', kinase, st).
enzyme_class('ATR', kinase, st).
enzyme_class('AURKA', kinase, st).
enzyme_class('AURKB', kinase, st).
enzyme_class('AURKC', kinase, st).
enzyme_class('AXL', kinase, y).
enzyme_class('BARK', kinase, unknown).
enzyme_class('BAZ1B', kinase, y).
enzyme_class('BCKDK', kinase, st).
enzyme_class('BCR', kinase, st).
enzyme_class('BLK', kinase, y).
enzyme_class('BMP2K', kinase, st).
enzyme_class('BMPR1A', kinase, st).
enzyme_class('BMPR1B', kinase, st).
enzyme_class('BMPR2', kinase, st).
enzyme_class('BMX', kinase, y).
enzyme_class('BRAF', kinase, st).
enzyme_class('BRSK1', kinase, st).
enzyme_class('BRSK2', kinase, st).
enzyme_class('BTK', kinase, y).
enzyme_class('BUB1', kinase, st).
enzyme_class('BUB1B', kinase, st).
enzyme_class('CAMK1', kinase, st).
enzyme_class('CAMK1D', kinase, st).
enzyme_class('CAMK1G', kinase, st).
enzyme_class('CAMK2A', kinase, st).
enzyme_class('CAMK2B', kinase, st).
enzyme_class('CAMK2D', kinase, st).
enzyme_class('CAMK2G', kinase, st).
enzyme_class('CAMK4', kinase, st).
enzyme_class('CAMKK1', kinase, st).
enzyme_class('CAMKK2', kinase, st).
enzyme_class('CAMKV', kinase, unknown).
enzyme_class('CASK', kinase, st).
enzyme_class('CDC42BPA', kinase, st).
enzyme_class('CDC42BPB', kinase, st).
enzyme_class('CDC42BPG', kinase, st).
enzyme_class('CDC7', kinase, st).
enzyme_class('CDK1', kinase, st).
enzyme_class('CDK10', kinase, st).
enzyme_class('CDK11A', kinase, st).
enzyme_class('CDK11B', kinase, st).
enzyme_class('CDK12', kinase, st).
enzyme_class('CDK13', kinase, st).
enzyme_class('CDK14', kinase, st).
enzyme_class('CDK15', kinase, st).
enzyme_class('CDK16', kinase, st).
enzyme_class('CDK17', kinase, st).
enzyme_class('CDK18', kinase, st).
enzyme_class('CDK19', kinase, st).
enzyme_class('CDK2', kinase, st).
enzyme_class('CDK20', kinase, st).
enzyme_class('CDK3', kinase, st).
enzyme_class('CDK4', kinase, st).
enzyme_class('CDK5', kinase, st).
enzyme_class('CDK6', kinase, st).
enzyme_class('CDK7', kinase, st).
enzyme_class('CDK8', kinase, st).
enzyme_class('CDK9', kinase, st).
enzyme_class('CDKL1', kinase, st).
enzyme_class('CDKL2', kinase, st).
enzyme_class('CDKL3', kinase, st).
enzyme_class('CDKL4', kinase, st).
enzyme_class('CDKL5', kinase, st).
enzyme_class('CHEK1', kinase, st).
enzyme_class('CHEK2', kinase, st).
enzyme_class('CHUK', kinase, st).
enzyme_class('CIITA', kinase, st).
enzyme_class('CILK1', kinase, st).
enzyme_class('CIT', kinase, st).
enzyme_class('CLK1', kinase, sty).
enzyme_class('CLK2', kinase, sty).
enzyme_class('CLK3', kinase, sty).
enzyme_class('CLK4', kinase, sty).
enzyme_class('COQ8A', kinase, unknown).
enzyme_class('COQ8B', kinase, unknown).
enzyme_class('CSF1R', kinase, y).
enzyme_class('CSK', kinase, y).
enzyme_class('CSNK1A1', kinase, st).
enzyme_class('CSNK1A1L', kinase, st).
enzyme_class('CSNK1D', kinase, st).
enzyme_class('CSNK1E', kinase, st).
enzyme_class('CSNK1G1', kinase, st).
enzyme_class('CSNK1G2', kinase, st).
enzyme_class('CSNK1G3', kinase, st).
enzyme_class('CSNK2A1', kinase, st).
enzyme_class('CSNK2A2', kinase, st).
enzyme_class('CSNK2A3', kinase, st).
enzyme_class('CSNK2B', kinase, unknown).
enzyme_class('DAPK1', kinase, st).
enzyme_class('DAPK2', kinase, st).
enzyme_class('DAPK3', kinase, st).
enzyme_class('DCAF1', kinase, st).
enzyme_class('DCLK1', kinase, st).
enzyme_class('DCLK2', kinase, st).
enzyme_class('DCLK3', kinase, st).
enzyme_class('DDR1', kinase, y).
enzyme_class('DDR2', kinase, y).
enzyme_class('DMPK', kinase, st).
enzyme_class('DSTYK', kinase, sty).
enzyme_class('DYRK1A', kinase, sty).
enzyme_class('DYRK1B', kinase, sty).
enzyme_class('DYRK2', kinase, sty).
enzyme_class('DYRK3', kinase, sty).
enzyme_class('DYRK4', kinase, sty).
enzyme_class('EEF2K', kinase, st).
enzyme_class('EGFR', kinase, y).
enzyme_class('EIF2AK1', kinase, st).
enzyme_class('EIF2AK2', kinase, sty).
enzyme_class('EIF2AK3', kinase, st).
enzyme_class('EIF2AK4', kinase, st).
enzyme_class('EPHA1', kinase, y).
enzyme_class('EPHA10', kinase, y).
enzyme_class('EPHA2', kinase, y).
enzyme_class('EPHA3', kinase, y).
enzyme_class('EPHA4', kinase, y).
enzyme_class('EPHA5', kinase, y).
enzyme_class('EPHA6', kinase, y).
enzyme_class('EPHA7', kinase, y).
enzyme_class('EPHA8', kinase, y).
enzyme_class('EPHB1', kinase, y).
enzyme_class('EPHB2', kinase, y).
enzyme_class('EPHB3', kinase, y).
enzyme_class('EPHB4', kinase, y).
enzyme_class('EPHB6', kinase, unknown).
enzyme_class('ERBB2', kinase, y).
enzyme_class('ERBB3', kinase, y).
enzyme_class('ERBB4', kinase, y).
enzyme_class('ERN1', kinase, st).
enzyme_class('ERN2', kinase, st).
enzyme_class('FAK2', kinase, unknown).
enzyme_class('FAM20C', kinase, st).
enzyme_class('FASTK', kinase, st).
enzyme_class('FER', kinase, y).
enzyme_class('FES', kinase, y).
enzyme_class('FGFR1', kinase, y).
enzyme_class('FGFR2', kinase, y).
enzyme_class('FGFR3', kinase, y).
enzyme_class('FGFR4', kinase, y).
enzyme_class('FGR', kinase, y).
enzyme_class('FLT', kinase, unknown).
enzyme_class('FLT1', kinase, y).
enzyme_class('FLT3', kinase, y).
enzyme_class('FLT4', kinase, y).
enzyme_class('FRK', kinase, y).
enzyme_class('FYN', kinase, y).
enzyme_class('GAK', kinase, st).
enzyme_class('GRK1', kinase, st).
enzyme_class('GRK2', kinase, st).
enzyme_class('GRK3', kinase, st).
enzyme_class('GRK4', kinase, st).
enzyme_class('GRK5', kinase, st).
enzyme_class('GRK6', kinase, st).
enzyme_class('GRK7', kinase, st).
enzyme_class('GSG2', kinase, unknown).
enzyme_class('GSK3A', kinase, st).
enzyme_class('GSK3B', kinase, st).
enzyme_class('GUCY2C', kinase, unknown).
enzyme_class('GUCY2D', kinase, unknown).
enzyme_class('GUCY2F', kinase, unknown).
enzyme_class('HASPIN', kinase, st).
enzyme_class('HCK', kinase, y).
enzyme_class('HIPK1', kinase, st).
enzyme_class('HIPK2', kinase, st).
enzyme_class('HIPK3', kinase, st).
enzyme_class('HIPK4', kinase, st).
enzyme_class('HUNK', kinase, st).
enzyme_class('IGF1R', kinase, y).
enzyme_class('IKBKB', kinase, st).
enzyme_class('IKBKE', kinase, st).
enzyme_class('ILK', kinase, st).
enzyme_class('INSR', kinase, y).
enzyme_class('INSRR', kinase, y).
enzyme_class('IRAK1', kinase, st).
enzyme_class('IRAK2', kinase, unknown).
enzyme_class('IRAK3', kinase, st).
enzyme_class('IRAK4', kinase, st).
enzyme_class('ITK', kinase, y).
enzyme_class('JAK1', kinase, y).
enzyme_class('JAK2', kinase, y).
enzyme_class('JAK3', kinase, y).
enzyme_class('KALRN', kinase, st).
enzyme_class('KDR', kinase, y).
enzyme_class('KIT', kinase, y).
enzyme_class('KSR1', kinase, st).
enzyme_class('KSR2', kinase, st).
enzyme_class('LATS1', kinase, st).
enzyme_class('LATS2', kinase, st).
enzyme_class('LCK', kinase, y).
enzyme_class('LIMK1', kinase, st).
enzyme_class('LIMK2', kinase, st).
enzyme_class('LMTK2', kinase, st).
enzyme_class('LMTK3', kinase, st).
enzyme_class('LRRK1', kinase, st).
enzyme_class('LRRK2', kinase, st).
enzyme_class('LTK', kinase, y).
enzyme_class('LYN', kinase, y).
enzyme_class('MAK', kinase, st).
enzyme_class('MAP2K1', kinase, sty).
enzyme_class('MAP2K2', kinase, sty).
enzyme_class('MAP2K3', kinase, sty).
enzyme_class('MAP2K4', kinase, sty).
enzyme_class('MAP2K5', kinase, sty).
enzyme_class('MAP2K6', kinase, sty).
enzyme_class('MAP2K7', kinase, sty).
enzyme_class('MAP3K1', kinase, st).
enzyme_class('MAP3K10', kinase, st).
enzyme_class('MAP3K11', kinase, st).
enzyme_class('MAP3K12', kinase, st).
enzyme_class('MAP3K13', kinase, st).
enzyme_class('MAP3K14', kinase, st).
enzyme_class('MAP3K15', kinase, st).
enzyme_class('MAP3K19', kinase, st).
enzyme_class('MAP3K2', kinase, st).
enzyme_class('MAP3K20', kinase, st).
enzyme_class('MAP3K21', kinase, st).
enzyme_class('MAP3K3', kinase, st).
enzyme_class('MAP3K4', kinase, st).
enzyme_class('MAP3K5', kinase, st).
enzyme_class('MAP3K6', kinase, st).
enzyme_class('MAP3K7', kinase, st).
enzyme_class('MAP3K8', kinase, st).
enzyme_class('MAP3K9', kinase, st).
enzyme_class('MAP4K1', kinase, st).
enzyme_class('MAP4K2', kinase, st).
enzyme_class('MAP4K3', kinase, st).
enzyme_class('MAP4K4', kinase, st).
enzyme_class('MAP4K5', kinase, st).
enzyme_class('MAPK1', kinase, st).
enzyme_class('MAPK10', kinase, st).
enzyme_class('MAPK11', kinase, st).
enzyme_class('MAPK12', kinase, st).
enzyme_class('MAPK13', kinase, st).
enzyme_class('MAPK14', kinase, st).
enzyme_class('MAPK15', kinase, st).
enzyme_class('MAPK3', kinase, st).
enzyme_class('MAPK4', kinase, st).
enzyme_class('MAPK6', kinase, st).
enzyme_class('MAPK7', kinase, st).
enzyme_class('MAPK8', kinase, st).
enzyme_class('MAPK9', kinase, st).
enzyme_class('MAPKAPK2', kinase, st).
enzyme_class('MAPKAPK3', kinase, st).
enzyme_class('MAPKAPK5', kinase, st).
enzyme_class('MARK1', kinase, st).
enzyme_class('MARK2', kinase, st).
enzyme_class('MARK3', kinase, st).
enzyme_class('MARK4', kinase, st).
enzyme_class('MAST1', kinase, st).
enzyme_class('MAST2', kinase, st).
enzyme_class('MAST3', kinase, st).
enzyme_class('MAST4', kinase, st).
enzyme_class('MASTL', kinase, st).
enzyme_class('MATK', kinase, y).
enzyme_class('MELK', kinase, sty).
enzyme_class('MERTK', kinase, y).
enzyme_class('MET', kinase, y).
enzyme_class('MINK1', kinase, st).
enzyme_class('MKNK1', kinase, st).
enzyme_class('MKNK2', kinase, st).
enzyme_class('MLKL', kinase, unknown).
enzyme_class('MOK', kinase, st).
enzyme_class('MOS', kinase, st).
enzyme_class('MST1', kinase, unknown).
enzyme_class('MST1R', kinase, y).
enzyme_class('MTOR', kinase, st).
enzyme_class('MUSK', kinase, y).
enzyme_class('MYLK', kinase, st).
enzyme_class('MYLK2', kinase, st).
enzyme_class('MYLK3', kinase, st).
enzyme_class('MYLK4', kinase, st).
enzyme_class('MYO3A', kinase, st).
enzyme_class('MYO3B', kinase, st).
enzyme_class('NEK1', kinase, st).
enzyme_class('NEK10', kinase, st).
enzyme_class('NEK11', kinase, st).
enzyme_class('NEK2', kinase, st).
enzyme_class('NEK3', kinase, st).
enzyme_class('NEK4', kinase, st).
enzyme_class('NEK5', kinase, st).
enzyme_class('NEK6', kinase, st).
enzyme_class('NEK7', kinase, st).
enzyme_class('NEK8', kinase, st).
enzyme_class('NEK9', kinase, st).
enzyme_class('NIM1K', kinase, st).
enzyme_class('NLK', kinase, st).
enzyme_class('NPR1', kinase, unknown).
enzyme_class('NPR2', kinase, unknown).
enzyme_class('NRBP1', kinase, unknown).
enzyme_class('NRBP2', kinase, unknown).
enzyme_class('NRK', kinase, st).
enzyme_class('NTRK1', kinase, y).
enzyme_class('NTRK2', kinase, y).
enzyme_class('NTRK3', kinase, y).
enzyme_class('NUAK1', kinase, st).
enzyme_class('NUAK2', kinase, st).
enzyme_class('OBSCN', kinase, st).
enzyme_class('OXSR1', kinase, st).
enzyme_class('PAK1', kinase, st).
enzyme_class('PAK2', kinase, st).
enzyme_class('PAK3', kinase, st).
enzyme_class('PAK4', kinase, st).
enzyme_class('PAK5', kinase, st).
enzyme_class('PAK6', kinase, st).
enzyme_class('PAN3', kinase, unknown).
enzyme_class('PASK', kinase, st).
enzyme_class('PBK', kinase, sty).
enzyme_class('PDGFRA', kinase, y).
enzyme_class('PDGFRB', kinase, y).
enzyme_class('PDIK1L', kinase, st).
enzyme_class('PDK1', kinase, st).
enzyme_class('PDK2', kinase, st).
enzyme_class('PDK3', kinase, st).
enzyme_class('PDK4', kinase, st).
enzyme_class('PDPK1', kinase, st).
enzyme_class('PDPK2P', kinase, st).
enzyme_class('PEAK1', kinase, unknown).
enzyme_class('PEAK3', kinase, unknown).
enzyme_class('PHKA1', kinase, unknown).
enzyme_class('PHKB', kinase, unknown).
enzyme_class('PHKG1', kinase, st).
enzyme_class('PHKG2', kinase, st).
enzyme_class('PIK3C2A', kinase, unknown).
enzyme_class('PIK3CA', kinase, st).
enzyme_class('PIK3CB', kinase, unknown).
enzyme_class('PIK3CD', kinase, unknown).
enzyme_class('PIK3CG', kinase, st).
enzyme_class('PIK3R4', kinase, st).
enzyme_class('PIM1', kinase, st).
enzyme_class('PIM2', kinase, st).
enzyme_class('PIM3', kinase, st).
enzyme_class('PINK1', kinase, st).
enzyme_class('PKDCC', kinase, y).
enzyme_class('PKMYT1', kinase, st).
enzyme_class('PKN1', kinase, st).
enzyme_class('PKN2', kinase, st).
enzyme_class('PKN3', kinase, st).
enzyme_class('PLK1', kinase, st).
enzyme_class('PLK2', kinase, st).
enzyme_class('PLK3', kinase, st).
enzyme_class('PLK4', kinase, st).
enzyme_class('PLK5', kinase, unknown).
enzyme_class('PNCK', kinase, st).
enzyme_class('POMK', kinase, unknown).
enzyme_class('PRAG1', kinase, unknown).
enzyme_class('PRKAA1', kinase, st).
enzyme_class('PRKAA2', kinase, st).
enzyme_class('PRKAB1', kinase, unknown).
enzyme_class('PRKACA', kinase, st).
enzyme_class('PRKACB', kinase, st).
enzyme_class('PRKACG', kinase, st).
enzyme_class('PRKCA', kinase, st).
enzyme_class('PRKCB', kinase, st).
enzyme_class('PRKCD', kinase, sty).
enzyme_class('PRKCE', kinase, st).
enzyme_class('PRKCG', kinase, st).
enzyme_class('PRKCH', kinase, st).
enzyme_class('PRKCI', kinase, st).
enzyme_class('PRKCQ', kinase, st).
enzyme_class('PRKCZ', kinase, st).
enzyme_class('PRKD1', kinase, st).
enzyme_class('PRKD2', kinase, st).
enzyme_class('PRKD3', kinase, st).
enzyme_class('PRKDC', kinase, st).
enzyme_class('PRKG1', kinase, st).
enzyme_class('PRKG2', kinase, st).
enzyme_class('PRKX', kinase, st).
enzyme_class('PRKY', kinase, st).
enzyme_class('PRPF4B', kinase, st).
enzyme_class('PRPK', kinase, unknown).
enzyme_class('PSKH1', kinase, st).
enzyme_class('PSKH2', kinase, st).
enzyme_class('PTK2', kinase, y).
enzyme_class('PTK2B', kinase, y).
enzyme_class('PTK6', kinase, y).
enzyme_class('PTK7', kinase, unknown).
enzyme_class('PXK', kinase, unknown).
enzyme_class('RAF1', kinase, st).
enzyme_class('RET', kinase, y).
enzyme_class('RIOK1', kinase, st).
enzyme_class('RIOK2', kinase, st).
enzyme_class('RIOK3', kinase, st).
enzyme_class('RIPK1', kinase, st).
enzyme_class('RIPK2', kinase, sty).
enzyme_class('RIPK3', kinase, st).
enzyme_class('RIPK4', kinase, st).
enzyme_class('RNASEL', kinase, unknown).
enzyme_class('ROCK1', kinase, st).
enzyme_class('ROCK2', kinase, st).
enzyme_class('ROR1', kinase, unknown).
enzyme_class('ROR2', kinase, y).
enzyme_class('ROS1', kinase, y).
enzyme_class('RPS6KA1', kinase, st).
enzyme_class('RPS6KA2', kinase, st).
enzyme_class('RPS6KA3', kinase, st).
enzyme_class('RPS6KA4', kinase, st).
enzyme_class('RPS6KA5', kinase, st).
enzyme_class('RPS6KA6', kinase, st).
enzyme_class('RPS6KB1', kinase, st).
enzyme_class('RPS6KB2', kinase, st).
enzyme_class('RPS6KC1', kinase, st).
enzyme_class('RPS6KL1', kinase, st).
enzyme_class('RSKR', kinase, st).
enzyme_class('RYK', kinase, y).
enzyme_class('SBK1', kinase, st).
enzyme_class('SBK2', kinase, st).
enzyme_class('SBK3', kinase, st).
enzyme_class('SCYL1', kinase, unknown).
enzyme_class('SCYL2', kinase, unknown).
enzyme_class('SCYL3', kinase, unknown).
enzyme_class('SGK1', kinase, st).
enzyme_class('SGK2', kinase, st).
enzyme_class('SGK3', kinase, st).
enzyme_class('SIK1', kinase, st).
enzyme_class('SIK1B', kinase, st).
enzyme_class('SIK2', kinase, st).
enzyme_class('SIK3', kinase, st).
enzyme_class('SLK', kinase, st).
enzyme_class('SMG1', kinase, st).
enzyme_class('SNRK', kinase, st).
enzyme_class('SPEG', kinase, st).
enzyme_class('SRC', kinase, y).
enzyme_class('SRMS', kinase, y).
enzyme_class('SRPK1', kinase, st).
enzyme_class('SRPK2', kinase, st).
enzyme_class('SRPK3', kinase, st).
enzyme_class('STK10', kinase, st).
enzyme_class('STK11', kinase, st).
enzyme_class('STK16', kinase, sty).
enzyme_class('STK17A', kinase, st).
enzyme_class('STK17B', kinase, st).
enzyme_class('STK19', kinase, st).
enzyme_class('STK24', kinase, st).
enzyme_class('STK25', kinase, st).
enzyme_class('STK26', kinase, st).
enzyme_class('STK3', kinase, st).
enzyme_class('STK31', kinase, st).
enzyme_class('STK32A', kinase, st).
enzyme_class('STK32B', kinase, st).
enzyme_class('STK32C', kinase, st).
enzyme_class('STK33', kinase, st).
enzyme_class('STK35', kinase, st).
enzyme_class('STK36', kinase, st).
enzyme_class('STK38', kinase, st).
enzyme_class('STK38L', kinase, st).
enzyme_class('STK39', kinase, st).
enzyme_class('STK4', kinase, st).
enzyme_class('STK40', kinase, st).
enzyme_class('STKLD1', kinase, unknown).
enzyme_class('STRADA', kinase, unknown).
enzyme_class('STRADB', kinase, unknown).
enzyme_class('STYK1', kinase, y).
enzyme_class('SYK', kinase, y).
enzyme_class('TAF1', kinase, st).
enzyme_class('TAOK1', kinase, st).
enzyme_class('TAOK2', kinase, st).
enzyme_class('TAOK3', kinase, st).
enzyme_class('TBCK', kinase, unknown).
enzyme_class('TBK1', kinase, st).
enzyme_class('TEC', kinase, y).
enzyme_class('TEK', kinase, y).
enzyme_class('TESK1', kinase, sty).
enzyme_class('TESK2', kinase, sty).
enzyme_class('TEX14', kinase, unknown).
enzyme_class('TGFBR1', kinase, st).
enzyme_class('TGFBR2', kinase, st).
enzyme_class('TIE1', kinase, y).
enzyme_class('TLK1', kinase, st).
enzyme_class('TLK2', kinase, st).
enzyme_class('TNIK', kinase, st).
enzyme_class('TNK1', kinase, y).
enzyme_class('TNK2', kinase, sty).
enzyme_class('TNNI3K', kinase, st).
enzyme_class('TP53RK', kinase, st).
enzyme_class('TRIB1', kinase, unknown).
enzyme_class('TRIB2', kinase, unknown).
enzyme_class('TRIB3', kinase, unknown).
enzyme_class('TRIO', kinase, st).
enzyme_class('TRPM6', kinase, st).
enzyme_class('TRPM7', kinase, st).
enzyme_class('TSSK1B', kinase, st).
enzyme_class('TSSK2', kinase, st).
enzyme_class('TSSK3', kinase, st).
enzyme_class('TSSK4', kinase, st).
enzyme_class('TSSK6', kinase, st).
enzyme_class('TTBK1', kinase, st).
enzyme_class('TTBK2', kinase, st).
enzyme_class('TTK', kinase, sty).
enzyme_class('TTN', kinase, st).
enzyme_class('TXK', kinase, y).
enzyme_class('TYK2', kinase, y).
enzyme_class('TYRO3', kinase, y).
enzyme_class('UHMK1', kinase, st).
enzyme_class('ULK1', kinase, st).
enzyme_class('ULK2', kinase, st).
enzyme_class('ULK3', kinase, st).
enzyme_class('ULK4', kinase, st).
enzyme_class('VRK1', kinase, st).
enzyme_class('VRK2', kinase, st).
enzyme_class('VRK3', kinase, unknown).
enzyme_class('WEE1', kinase, y).
enzyme_class('WEE2', kinase, y).
enzyme_class('WNK1', kinase, st).
enzyme_class('WNK2', kinase, st).
enzyme_class('WNK3', kinase, st).
enzyme_class('WNK4', kinase, st).
enzyme_class('YES1', kinase, y).
enzyme_class('ZAP70', kinase, y).
enzyme_class('ACP1', phosphatase, y).
enzyme_class('CDC14A', phosphatase, sty).
enzyme_class('CDC14B', phosphatase, sty).
enzyme_class('CDC14C', phosphatase, sty).
enzyme_class('CDC25A', phosphatase, y).
enzyme_class('CDC25B', phosphatase, y).
enzyme_class('CDC25C', phosphatase, y).
enzyme_class('CDKN3', phosphatase, sty).
enzyme_class('CPPED1', phosphatase, st).
enzyme_class('CTDNEP1', phosphatase, st).
enzyme_class('CTDP1', phosphatase, st).
enzyme_class('CTDSP1', phosphatase, st).
enzyme_class('CTDSP2', phosphatase, st).
enzyme_class('CTDSPL', phosphatase, st).
enzyme_class('DNAJC6', phosphatase, y).
enzyme_class('DUPD1', phosphatase, sty).
enzyme_class('DUSP1', phosphatase, sty).
enzyme_class('DUSP10', phosphatase, sty).
enzyme_class('DUSP12', phosphatase, sty).
enzyme_class('DUSP13', phosphatase, sty).
enzyme_class('DUSP14', phosphatase, sty).
enzyme_class('DUSP15', phosphatase, sty).
enzyme_class('DUSP16', phosphatase, sty).
enzyme_class('DUSP18', phosphatase, sty).
enzyme_class('DUSP19', phosphatase, sty).
enzyme_class('DUSP2', phosphatase, sty).
enzyme_class('DUSP21', phosphatase, sty).
enzyme_class('DUSP22', phosphatase, sty).
enzyme_class('DUSP23', phosphatase, sty).
enzyme_class('DUSP26', phosphatase, sty).
enzyme_class('DUSP28', phosphatase, sty).
enzyme_class('DUSP3', phosphatase, sty).
enzyme_class('DUSP4', phosphatase, sty).
enzyme_class('DUSP5', phosphatase, sty).
enzyme_class('DUSP6', phosphatase, sty).
enzyme_class('DUSP7', phosphatase, sty).
enzyme_class('DUSP8', phosphatase, sty).
enzyme_class('DUSP9', phosphatase, sty).
enzyme_class('EPM2A', phosphatase, sty).
enzyme_class('EYA1', phosphatase, sty).
enzyme_class('EYA2', phosphatase, y).
enzyme_class('EYA3', phosphatase, y).
enzyme_class('EYA4', phosphatase, y).
enzyme_class('ILKAP', phosphatase, st).
enzyme_class('MDP1', phosphatase, y).
enzyme_class('MTMR3', phosphatase, y).
enzyme_class('MTMR4', phosphatase, y).
enzyme_class('PGAM5', phosphatase, st).
enzyme_class('PGP', phosphatase, y).
enzyme_class('PHLPP1', phosphatase, st).
enzyme_class('PHLPP2', phosphatase, st).
enzyme_class('PPEF1', phosphatase, st).
enzyme_class('PPEF2', phosphatase, st).
enzyme_class('PPM1A', phosphatase, st).
enzyme_class('PPM1B', phosphatase, st).
enzyme_class('PPM1D', phosphatase, st).
enzyme_class('PPM1E', phosphatase, st).
enzyme_class('PPM1F', phosphatase, st).
enzyme_class('PPM1G', phosphatase, st).
enzyme_class('PPM1H', phosphatase, st).
enzyme_class('PPM1J', phosphatase, st).
enzyme_class('PPM1K', phosphatase, st).
enzyme_class('PPM1L', phosphatase, st).
enzyme_class('PPM1M', phosphatase, st).
enzyme_class('PPM1N', phosphatase, st).
enzyme_class('PPP1CA', phosphatase, st).
enzyme_class('PPP1CB', phosphatase, st).
enzyme_class('PPP1CC', phosphatase, st).
enzyme_class('PPP2CA', phosphatase, st).
enzyme_class('PPP2CB', phosphatase, st).
enzyme_class('PPP3CA', phosphatase, st).
enzyme_class('PPP3CB', phosphatase, st).
enzyme_class('PPP3CC', phosphatase, st).
enzyme_class('PPP4C', phosphatase, st).
enzyme_class('PPP5C', phosphatase, st).
enzyme_class('PPP6C', phosphatase, st).
enzyme_class('PPTC7', phosphatase, st).
enzyme_class('PTEN', phosphatase, sty).
enzyme_class('PTP4A1', phosphatase, y).
enzyme_class('PTP4A2', phosphatase, y).
enzyme_class('PTP4A3', phosphatase, y).
enzyme_class('PTPMT1', phosphatase, sty).
enzyme_class('PTPN1', phosphatase, y).
enzyme_class('PTPN11', phosphatase, y).
enzyme_class('PTPN12', phosphatase, y).
enzyme_class('PTPN13', phosphatase, y).
enzyme_class('PTPN14', phosphatase, y).
enzyme_class('PTPN18', phosphatase, y).
enzyme_class('PTPN2', phosphatase, y).
enzyme_class('PTPN20', phosphatase, y).
enzyme_class('PTPN21', phosphatase, y).
enzyme_class('PTPN22', phosphatase, y).
enzyme_class('PTPN23', phosphatase, y).
enzyme_class('PTPN3', phosphatase, y).
enzyme_class('PTPN4', phosphatase, y).
enzyme_class('PTPN5', phosphatase, y).
enzyme_class('PTPN6', phosphatase, y).
enzyme_class('PTPN7', phosphatase, y).
enzyme_class('PTPN9', phosphatase, y).
enzyme_class('PTPRA', phosphatase, y).
enzyme_class('PTPRB', phosphatase, y).
enzyme_class('PTPRC', phosphatase, y).
enzyme_class('PTPRD', phosphatase, y).
enzyme_class('PTPRE', phosphatase, y).
enzyme_class('PTPRF', phosphatase, y).
enzyme_class('PTPRG', phosphatase, y).
enzyme_class('PTPRH', phosphatase, y).
enzyme_class('PTPRJ', phosphatase, y).
enzyme_class('PTPRK', phosphatase, y).
enzyme_class('PTPRM', phosphatase, y).
enzyme_class('PTPRN2', phosphatase, y).
enzyme_class('PTPRO', phosphatase, y).
enzyme_class('PTPRQ', phosphatase, y).
enzyme_class('PTPRR', phosphatase, y).
enzyme_class('PTPRS', phosphatase, y).
enzyme_class('PTPRT', phosphatase, y).
enzyme_class('PTPRU', phosphatase, y).
enzyme_class('PTPRZ1', phosphatase, y).
enzyme_class('RPAP2', phosphatase, st).
enzyme_class('SSH1', phosphatase, sty).
enzyme_class('SSH2', phosphatase, sty).
enzyme_class('SSH3', phosphatase, sty).
enzyme_class('SSU72', phosphatase, st).
enzyme_class('TNS2', phosphatase, y).
enzyme_class('TPTE', phosphatase, y).
enzyme_class('UBASH3B', phosphatase, y).
enzyme_class('UBLCP1', phosphatase, st).
