expressed_in('NRBP1', 'MCF7').
expressed_in('NRBP1', 'HL60').
expressed_in('NRBP1', 'NTERA2').
expressed_in('PAK4', 'MCF7').
expressed_in('PAK4', 'HL60').
expressed_in('PAK4', 'NTERA2').
expressed_in('NRK', 'NTERA2').
expressed_in('BMP2K', 'MCF7').
expressed_in('BMP2K', 'HL60').
expressed_in('BMP2K', 'NTERA2').
expressed_in('CDK6', 'HL60').
expressed_in('CDK6', 'NTERA2').
expressed_in('CDK15', 'MCF7').
expressed_in('CDK15', 'NTERA2').
expressed_in('CDC7', 'NTERA2').
expressed_in('CDK3', 'MCF7').
expressed_in('CDK3', 'HL60').
expressed_in('CDK3', 'NTERA2').
expressed_in('CDK14', 'HL60').
expressed_in('CDK14', 'NTERA2').
expressed_in('CDK16', 'MCF7').
expressed_in('CDK16', 'HL60').
expressed_in('CDK16', 'NTERA2').
expressed_in('CDK17', 'MCF7').
expressed_in('CDK17', 'HL60').
expressed_in('CDK17', 'NTERA2').
expressed_in('CDK18', 'MCF7').
expressed_in('CDK18', 'HL60').
expressed_in('CDK18', 'NTERA2').
expressed_in('CDK13', 'MCF7').
expressed_in('CDK13', 'HL60').
expressed_in('CDK13', 'NTERA2').
expressed_in('CDK9', 'MCF7').
expressed_in('CDK9', 'HL60').
expressed_in('CDK9', 'NTERA2').
expressed_in('CDK7', 'MCF7').
expressed_in('CDK7', 'HL60').
expressed_in('CDK7', 'NTERA2').
expressed_in('CDK4', 'MCF7').
expressed_in('CDK4', 'NTERA2').
expressed_in('CDKL5', 'NTERA2').
expressed_in('CDK1', 'MCF7').
expressed_in('CDK1', 'HL60').
expressed_in('CDK1', 'NTERA2').
expressed_in('CDK5', 'MCF7').
expressed_in('CDK5', 'HL60').
expressed_in('CDK5', 'NTERA2').
expressed_in('CDK20', 'MCF7').
expressed_in('CDK20', 'HL60').
expressed_in('CDK20', 'NTERA2').
expressed_in('CDK11A', 'MCF7').
expressed_in('CDK11A', 'HL60').
expressed_in('CDK11A', 'NTERA2').
expressed_in('CDK2', 'MCF7').
expressed_in('CDK2', 'HL60').
expressed_in('CDK2', 'NTERA2').
expressed_in('CDK12', 'MCF7').
expressed_in('CDK12', 'HL60').
expressed_in('CDK12', 'NTERA2').
expressed_in('PAK2', 'MCF7').
expressed_in('PAK2', 'HL60').
expressed_in('PAK2', 'NTERA2').
expressed_in('PAK3', 'MCF7').
expressed_in('PAK3', 'HL60').
expressed_in('PAK3', 'NTERA2').
expressed_in('PAN3', 'MCF7').
expressed_in('PAN3', 'HL60').
expressed_in('PAN3', 'NTERA2').
expressed_in('NRBP2', 'MCF7').
expressed_in('NRBP2', 'HL60').
expressed_in('NRBP2', 'NTERA2').
expressed_in('OXSR1', 'MCF7').
expressed_in('OXSR1', 'HL60').
expressed_in('OXSR1', 'NTERA2').
expressed_in('SCYL3', 'MCF7').
expressed_in('SCYL3', 'HL60').
expressed_in('SCYL3', 'NTERA2').
expressed_in('PKMYT1', 'MCF7').
expressed_in('PKMYT1', 'HL60').
expressed_in('PKMYT1', 'NTERA2').
expressed_in('PRAG1', 'MCF7').
expressed_in('PRAG1', 'NTERA2').
expressed_in('PIK3CA', 'MCF7').
expressed_in('PIK3CA', 'HL60').
expressed_in('PIK3CA', 'NTERA2').
expressed_in('PHKG2', 'MCF7').
expressed_in('PHKG2', 'HL60').
expressed_in('PHKG2', 'NTERA2').
expressed_in('PKN2', 'MCF7').
expressed_in('PKN2', 'HL60').
expressed_in('PKN2', 'NTERA2').
expressed_in('PIK3CB', 'MCF7').
expressed_in('PIK3CB', 'HL60').
expressed_in('PIK3CB', 'NTERA2').
expressed_in('PLK1', 'MCF7').
expressed_in('PLK1', 'HL60').
expressed_in('PLK1', 'NTERA2').
expressed_in('RAF1', 'MCF7').
expressed_in('RAF1', 'HL60').
expressed_in('RAF1', 'NTERA2').
expressed_in('RIOK1', 'MCF7').
expressed_in('RIOK1', 'HL60').
expressed_in('RIOK1', 'NTERA2').
expressed_in('RIPK1', 'MCF7').
expressed_in('RIPK1', 'HL60').
expressed_in('RIPK1', 'NTERA2').
expressed_in('RIPK2', 'MCF7').
expressed_in('RIPK2', 'HL60').
expressed_in('RIPK2', 'NTERA2').
expressed_in('RIPK3', 'HL60').
expressed_in('RET', 'MCF7').
expressed_in('PDPK2P', 'MCF7').
expressed_in('PDPK2P', 'HL60').
expressed_in('PDPK2P', 'NTERA2').
expressed_in('PAK1', 'MCF7').
expressed_in('PAK1', 'HL60').
expressed_in('PAK1', 'NTERA2').
expressed_in('PDGFRB', 'MCF7').
expressed_in('PDGFRB', 'HL60').
expressed_in('PDGFRB', 'NTERA2').
expressed_in('PIK3R4', 'MCF7').
expressed_in('PIK3R4', 'HL60').
expressed_in('PIK3R4', 'NTERA2').
expressed_in('PKN1', 'MCF7').
expressed_in('PKN1', 'HL60').
expressed_in('PKN1', 'NTERA2').
expressed_in('NEK1', 'MCF7').
expressed_in('NEK1', 'HL60').
expressed_in('NEK1', 'NTERA2').
expressed_in('MYLK', 'MCF7').
expressed_in('MYLK', 'HL60').
expressed_in('MYLK', 'NTERA2').
expressed_in('NEK9', 'MCF7').
expressed_in('NEK9', 'HL60').
expressed_in('NEK9', 'NTERA2').
expressed_in('NEK3', 'MCF7').
expressed_in('NEK3', 'NTERA2').
expressed_in('PTK7', 'NTERA2').
expressed_in('PRKDC', 'MCF7').
expressed_in('PRKDC', 'HL60').
expressed_in('PRKDC', 'NTERA2').
expressed_in('PRPF4B', 'MCF7').
expressed_in('PRPF4B', 'HL60').
expressed_in('PRPF4B', 'NTERA2').
expressed_in('PEAK1', 'MCF7').
expressed_in('PEAK1', 'HL60').
expressed_in('PEAK1', 'NTERA2').
expressed_in('AKT3', 'MCF7').
expressed_in('AKT3', 'NTERA2').
expressed_in('TNK2', 'MCF7').
expressed_in('TNK2', 'HL60').
expressed_in('TNK2', 'NTERA2').
expressed_in('PRKAA1', 'HL60').
expressed_in('ABL2', 'MCF7').
expressed_in('ABL2', 'HL60').
expressed_in('ABL2', 'NTERA2').
expressed_in('ABL1', 'MCF7').
expressed_in('ABL1', 'HL60').
expressed_in('ABL1', 'NTERA2').
expressed_in('AAK1', 'MCF7').
expressed_in('AAK1', 'HL60').
expressed_in('AAK1', 'NTERA2').
expressed_in('PRKAA2', 'NTERA2').
expressed_in('SIK2', 'MCF7').
expressed_in('SIK2', 'HL60').
expressed_in('SIK2', 'NTERA2').
expressed_in('SIK3', 'MCF7').
expressed_in('SIK3', 'HL60').
expressed_in('SIK3', 'NTERA2').
expressed_in('SPEG', 'MCF7').
expressed_in('SPEG', 'HL60').
expressed_in('SPEG', 'NTERA2').
expressed_in('STK32C', 'MCF7').
expressed_in('STK32C', 'NTERA2').
expressed_in('STK33', 'MCF7').
expressed_in('STK33', 'HL60').
expressed_in('STK33', 'NTERA2').
expressed_in('STK3', 'MCF7').
expressed_in('STK3', 'HL60').
expressed_in('STK3', 'NTERA2').
expressed_in('STK4', 'MCF7').
expressed_in('STK4', 'HL60').
expressed_in('STK4', 'NTERA2').
expressed_in('STK24', 'MCF7').
expressed_in('STK24', 'HL60').
expressed_in('STK24', 'NTERA2').
expressed_in('STK17A', 'MCF7').
expressed_in('STK17A', 'HL60').
expressed_in('STK17A', 'NTERA2').
expressed_in('STK25', 'MCF7').
expressed_in('STK25', 'HL60').
expressed_in('STK25', 'NTERA2').
expressed_in('STK26', 'MCF7').
expressed_in('STK26', 'HL60').
expressed_in('STK26', 'NTERA2').
expressed_in('STK38', 'MCF7').
expressed_in('STK38', 'HL60').
expressed_in('STK38', 'NTERA2').
expressed_in('SRC', 'MCF7').
expressed_in('SRC', 'NTERA2').
expressed_in('STK38L', 'MCF7').
expressed_in('STK38L', 'HL60').
expressed_in('STK38L', 'NTERA2').
expressed_in('STK10', 'MCF7').
expressed_in('STK10', 'HL60').
expressed_in('STK10', 'NTERA2').
expressed_in('STK11', 'MCF7').
expressed_in('STK11', 'HL60').
expressed_in('STK11', 'NTERA2').
expressed_in('STK39', 'MCF7').
expressed_in('STK39', 'HL60').
expressed_in('STK39', 'NTERA2').
expressed_in('ROCK2', 'MCF7').
expressed_in('ROCK2', 'HL60').
expressed_in('ROCK2', 'NTERA2').
expressed_in('ROR1', 'MCF7').
expressed_in('ROR1', 'HL60').
expressed_in('ROR1', 'NTERA2').
expressed_in('RPS6KL1', 'MCF7').
expressed_in('RPS6KL1', 'HL60').
expressed_in('RPS6KL1', 'NTERA2').
expressed_in('SRPK3', 'HL60').
expressed_in('SLK', 'MCF7').
expressed_in('SLK', 'HL60').
expressed_in('SLK', 'NTERA2').
expressed_in('POMK', 'NTERA2').
expressed_in('SNRK', 'MCF7').
expressed_in('SNRK', 'HL60').
expressed_in('SNRK', 'NTERA2').
expressed_in('SMG1', 'MCF7').
expressed_in('SMG1', 'HL60').
expressed_in('SMG1', 'NTERA2').
expressed_in('ROCK1', 'MCF7').
expressed_in('ROCK1', 'HL60').
expressed_in('ROCK1', 'NTERA2').
expressed_in('TESK2', 'MCF7').
expressed_in('TESK2', 'NTERA2').
expressed_in('TNK1', 'MCF7').
expressed_in('TNK1', 'NTERA2').
expressed_in('TTN', 'MCF7').
expressed_in('TTN', 'HL60').
expressed_in('TTN', 'NTERA2').
expressed_in('TLK2', 'MCF7').
expressed_in('TLK2', 'HL60').
expressed_in('TLK2', 'NTERA2').
expressed_in('TBK1', 'MCF7').
expressed_in('SRPK1', 'MCF7').
expressed_in('SRPK1', 'HL60').
expressed_in('SRPK1', 'NTERA2').
expressed_in('SRPK2', 'MCF7').
expressed_in('SRPK2', 'HL60').
expressed_in('SRPK2', 'NTERA2').
expressed_in('TAOK3', 'MCF7').
expressed_in('TAOK3', 'HL60').
expressed_in('TAOK3', 'NTERA2').
expressed_in('TAOK1', 'MCF7').
expressed_in('TAOK1', 'HL60').
expressed_in('TAOK1', 'NTERA2').
expressed_in('SCYL2', 'MCF7').
expressed_in('SCYL2', 'HL60').
expressed_in('SCYL2', 'NTERA2').
expressed_in('TLK1', 'MCF7').
expressed_in('TLK1', 'HL60').
expressed_in('TLK1', 'NTERA2').
expressed_in('TNNI3K', 'MCF7').
expressed_in('TNNI3K', 'HL60').
expressed_in('TNNI3K', 'NTERA2').
expressed_in('TNIK', 'MCF7').
expressed_in('TNIK', 'HL60').
expressed_in('TNIK', 'NTERA2').
expressed_in('TTBK1', 'MCF7').
expressed_in('TTBK1', 'HL60').
expressed_in('TTBK1', 'NTERA2').
expressed_in('TRIO', 'MCF7').
expressed_in('TRIO', 'HL60').
expressed_in('TRIO', 'NTERA2').
expressed_in('PBK', 'MCF7').
expressed_in('PBK', 'HL60').
expressed_in('PBK', 'NTERA2').
expressed_in('RIOK2', 'MCF7').
expressed_in('RIOK2', 'HL60').
expressed_in('RIOK2', 'NTERA2').
expressed_in('RNASEL', 'MCF7').
expressed_in('RNASEL', 'NTERA2').
expressed_in('NEK4', 'HL60').
expressed_in('CSK', 'MCF7').
expressed_in('CSK', 'HL60').
expressed_in('CSK', 'NTERA2').
expressed_in('CSNK2A3', 'MCF7').
expressed_in('CSNK2A3', 'HL60').
expressed_in('CSNK2A3', 'NTERA2').
expressed_in('CHEK1', 'MCF7').
expressed_in('CHEK1', 'HL60').
expressed_in('CHEK1', 'NTERA2').
expressed_in('CHEK2', 'MCF7').
expressed_in('CHEK2', 'HL60').
expressed_in('CHEK2', 'NTERA2').
expressed_in('CLK2', 'MCF7').
expressed_in('CLK2', 'HL60').
expressed_in('CLK2', 'NTERA2').
expressed_in('CLK3', 'MCF7').
expressed_in('CLK3', 'HL60').
expressed_in('CLK3', 'NTERA2').
expressed_in('CSNK2A1', 'MCF7').
expressed_in('CSNK2A1', 'HL60').
expressed_in('CSNK2A1', 'NTERA2').
expressed_in('CSNK2A2', 'MCF7').
expressed_in('CSNK2A2', 'HL60').
expressed_in('CSNK2A2', 'NTERA2').
expressed_in('CASK', 'MCF7').
expressed_in('CASK', 'HL60').
expressed_in('CASK', 'NTERA2').
expressed_in('EIF2AK2', 'MCF7').
expressed_in('EIF2AK2', 'HL60').
expressed_in('EIF2AK2', 'NTERA2').
expressed_in('EIF2AK3', 'MCF7').
expressed_in('EIF2AK3', 'HL60').
expressed_in('EIF2AK4', 'NTERA2').
expressed_in('EEF2K', 'MCF7').
expressed_in('EEF2K', 'HL60').
expressed_in('EEF2K', 'NTERA2').
expressed_in('PTK2', 'MCF7').
expressed_in('PTK2', 'HL60').
expressed_in('PTK2', 'NTERA2').
expressed_in('ERN1', 'MCF7').
expressed_in('ERN1', 'HL60').
expressed_in('ERN1', 'NTERA2').
expressed_in('EPHA1', 'MCF7').
expressed_in('EPHA1', 'NTERA2').
expressed_in('EPHB2', 'MCF7').
expressed_in('EPHB2', 'HL60').
expressed_in('EPHB2', 'NTERA2').
expressed_in('ERBB2', 'MCF7').
expressed_in('ERBB2', 'NTERA2').
expressed_in('FER', 'HL60').
expressed_in('FGFR3', 'NTERA2').
expressed_in('AURKA', 'MCF7').
expressed_in('AURKA', 'NTERA2').
expressed_in('BCKDK', 'MCF7').
expressed_in('BCKDK', 'HL60').
expressed_in('BCKDK', 'NTERA2').
expressed_in('ATR', 'MCF7').
expressed_in('ATR', 'HL60').
expressed_in('ATR', 'NTERA2').
expressed_in('AURKB', 'MCF7').
expressed_in('AURKB', 'NTERA2').
expressed_in('ATM', 'NTERA2').
expressed_in('AKT2', 'MCF7').
expressed_in('AKT2', 'HL60').
expressed_in('AKT2', 'NTERA2').
expressed_in('ARAF', 'MCF7').
expressed_in('ARAF', 'HL60').
expressed_in('ARAF', 'NTERA2').
expressed_in('NPR2', 'MCF7').
expressed_in('NPR2', 'HL60').
expressed_in('NPR2', 'NTERA2').
expressed_in('BTK', 'HL60').
expressed_in('BUB1', 'MCF7').
expressed_in('BUB1', 'HL60').
expressed_in('BUB1', 'NTERA2').
expressed_in('BUB1B', 'MCF7').
expressed_in('BUB1B', 'HL60').
expressed_in('BUB1B', 'NTERA2').
expressed_in('BRAF', 'MCF7').
expressed_in('BRAF', 'HL60').
expressed_in('BRAF', 'NTERA2').
expressed_in('BRSK2', 'MCF7').
expressed_in('BRSK2', 'HL60').
expressed_in('BRSK2', 'NTERA2').
expressed_in('CAMKV', 'NTERA2').
expressed_in('ALPK3', 'MCF7').
expressed_in('ALPK3', 'NTERA2').
expressed_in('EPHB4', 'MCF7').
expressed_in('EPHB4', 'HL60').
expressed_in('EPHB4', 'NTERA2').
expressed_in('DYRK2', 'MCF7').
expressed_in('DYRK2', 'HL60').
expressed_in('DYRK2', 'NTERA2').
expressed_in('EIF2AK1', 'MCF7').
expressed_in('EIF2AK1', 'NTERA2').
expressed_in('DYRK1A', 'MCF7').
expressed_in('DYRK1A', 'HL60').
expressed_in('DYRK1A', 'NTERA2').
expressed_in('ERBB3', 'MCF7').
expressed_in('DCLK1', 'NTERA2').
expressed_in('DAPK3', 'NTERA2').
expressed_in('CIT', 'MCF7').
expressed_in('CIT', 'HL60').
expressed_in('CIT', 'NTERA2').
expressed_in('FES', 'MCF7').
expressed_in('FES', 'HL60').
expressed_in('FYN', 'HL60').
expressed_in('FYN', 'NTERA2').
expressed_in('CLK1', 'MCF7').
expressed_in('CLK1', 'NTERA2').
expressed_in('CDK11B', 'MCF7').
expressed_in('CDK11B', 'HL60').
expressed_in('CDK11B', 'NTERA2').
expressed_in('CLK4', 'MCF7').
expressed_in('CLK4', 'HL60').
expressed_in('CLK4', 'NTERA2').
expressed_in('CHUK', 'MCF7').
expressed_in('IGF1R', 'MCF7').
expressed_in('IGF1R', 'NTERA2').
expressed_in('GSG2', 'MCF7').
expressed_in('GSG2', 'HL60').
expressed_in('GSG2', 'NTERA2').
expressed_in('CSNK1E', 'MCF7').
expressed_in('CSNK1E', 'HL60').
expressed_in('CSNK1E', 'NTERA2').
expressed_in('CAMK2B', 'MCF7').
expressed_in('CAMK2B', 'NTERA2').
expressed_in('JAK3', 'HL60').
expressed_in('KALRN', 'MCF7').
expressed_in('KALRN', 'HL60').
expressed_in('KALRN', 'NTERA2').
expressed_in('PRKACB', 'MCF7').
expressed_in('PRKACB', 'HL60').
expressed_in('PRKACB', 'NTERA2').
expressed_in('CAMK2D', 'MCF7').
expressed_in('CAMK2D', 'NTERA2').
expressed_in('IKBKB', 'HL60').
expressed_in('IKBKB', 'NTERA2').
expressed_in('IRAK1', 'MCF7').
expressed_in('IRAK1', 'HL60').
expressed_in('CAMK2G', 'MCF7').
expressed_in('CAMK2G', 'HL60').
expressed_in('CAMK2G', 'NTERA2').
expressed_in('CSNK1A1', 'MCF7').
expressed_in('CSNK1A1', 'HL60').
expressed_in('CSNK1A1', 'NTERA2').
expressed_in('CAMK1', 'HL60').
expressed_in('CAMK2A', 'MCF7').
expressed_in('CAMKK2', 'MCF7').
expressed_in('CAMKK2', 'HL60').
expressed_in('CAMKK2', 'NTERA2').
expressed_in('LYN', 'NTERA2').
expressed_in('MAP4K2', 'HL60').
expressed_in('MAP4K2', 'NTERA2').
expressed_in('MAP4K3', 'NTERA2').
expressed_in('PRKD1', 'MCF7').
expressed_in('PRKD1', 'NTERA2').
expressed_in('PRKD3', 'MCF7').
expressed_in('PRKD3', 'HL60').
expressed_in('PRKD3', 'NTERA2').
expressed_in('RPS6KA1', 'MCF7').
expressed_in('RPS6KA1', 'HL60').
expressed_in('RPS6KA1', 'NTERA2').
expressed_in('RPS6KA2', 'MCF7').
expressed_in('RPS6KA2', 'HL60').
expressed_in('RPS6KA2', 'NTERA2').
expressed_in('RPS6KA3', 'MCF7').
expressed_in('RPS6KA3', 'HL60').
expressed_in('RPS6KA3', 'NTERA2').
expressed_in('LATS1', 'MCF7').
expressed_in('LATS1', 'HL60').
expressed_in('LATS1', 'NTERA2').
expressed_in('MAP4K4', 'MCF7').
expressed_in('MAP4K4', 'HL60').
expressed_in('MAP4K4', 'NTERA2').
expressed_in('MAP3K2', 'MCF7').
expressed_in('MAP3K2', 'HL60').
expressed_in('MAP3K2', 'NTERA2').
expressed_in('LIMK1', 'MCF7').
expressed_in('LIMK1', 'HL60').
expressed_in('LIMK1', 'NTERA2').
expressed_in('PRKD2', 'MCF7').
expressed_in('PRKD2', 'HL60').
expressed_in('PRKD2', 'NTERA2').
expressed_in('LIMK2', 'MCF7').
expressed_in('LIMK2', 'HL60').
expressed_in('LIMK2', 'NTERA2').
expressed_in('RPS6KC1', 'MCF7').
expressed_in('RPS6KC1', 'HL60').
expressed_in('RPS6KC1', 'NTERA2').
expressed_in('ILK', 'MCF7').
expressed_in('ILK', 'HL60').
expressed_in('ILK', 'NTERA2').
expressed_in('IRAK4', 'HL60').
expressed_in('MINK1', 'MCF7').
expressed_in('MINK1', 'HL60').
expressed_in('MINK1', 'NTERA2').
expressed_in('MAPK7', 'NTERA2').
expressed_in('MAP2K4', 'MCF7').
expressed_in('MAP2K4', 'HL60').
expressed_in('MAP2K4', 'NTERA2').
expressed_in('MOK', 'MCF7').
expressed_in('MAP2K3', 'MCF7').
expressed_in('MAP2K3', 'HL60').
expressed_in('MAP2K3', 'NTERA2').
expressed_in('MAPK1', 'MCF7').
expressed_in('MAPK1', 'HL60').
expressed_in('MAPK1', 'NTERA2').
expressed_in('MAPK14', 'MCF7').
expressed_in('MAPK14', 'HL60').
expressed_in('MAPK14', 'NTERA2').
expressed_in('MLKL', 'MCF7').
expressed_in('MLKL', 'NTERA2').
expressed_in('MAP2K7', 'MCF7').
expressed_in('MAP2K7', 'HL60').
expressed_in('MAP2K7', 'NTERA2').
expressed_in('MATK', 'MCF7').
expressed_in('MATK', 'HL60').
expressed_in('MATK', 'NTERA2').
expressed_in('MAP3K3', 'MCF7').
expressed_in('MAP3K3', 'HL60').
expressed_in('MAP3K3', 'NTERA2').
expressed_in('MAP3K15', 'MCF7').
expressed_in('MAP3K15', 'HL60').
expressed_in('MAP3K15', 'NTERA2').
expressed_in('MAP3K20', 'MCF7').
expressed_in('MAP3K20', 'HL60').
expressed_in('MAP3K20', 'NTERA2').
expressed_in('LRRK1', 'MCF7').
expressed_in('LRRK1', 'HL60').
expressed_in('LRRK1', 'NTERA2').
expressed_in('MAK', 'MCF7').
expressed_in('MAK', 'HL60').
expressed_in('MAK', 'NTERA2').
expressed_in('MAPKAPK2', 'MCF7').
expressed_in('MAPKAPK2', 'HL60').
expressed_in('MAPKAPK2', 'NTERA2').
expressed_in('MAPKAPK3', 'MCF7').
expressed_in('MAPKAPK3', 'HL60').
expressed_in('MAPKAPK3', 'NTERA2').
expressed_in('MAPKAPK5', 'HL60').
expressed_in('MARK2', 'MCF7').
expressed_in('MARK2', 'HL60').
expressed_in('MARK2', 'NTERA2').
expressed_in('MARK3', 'MCF7').
expressed_in('MARK3', 'HL60').
expressed_in('MARK3', 'NTERA2').
expressed_in('MAP3K11', 'MCF7').
expressed_in('MAP3K11', 'HL60').
expressed_in('MAP3K11', 'NTERA2').
expressed_in('MAP3K7', 'MCF7').
expressed_in('MAP3K7', 'HL60').
expressed_in('MAP3K7', 'NTERA2').
expressed_in('MAP3K9', 'HL60').
expressed_in('MAP3K9', 'NTERA2').
expressed_in('MAST3', 'MCF7').
expressed_in('MAST3', 'HL60').
expressed_in('MAST3', 'NTERA2').
expressed_in('MARK1', 'NTERA2').
expressed_in('MAP4K5', 'MCF7').
expressed_in('MAP4K5', 'HL60').
expressed_in('MAP4K5', 'NTERA2').
expressed_in('MAP3K1', 'MCF7').
expressed_in('MAP3K1', 'HL60').
expressed_in('MAP3K1', 'NTERA2').
expressed_in('MAP3K21', 'MCF7').
expressed_in('MAP3K21', 'HL60').
expressed_in('MAP3K21', 'NTERA2').
expressed_in('MAST1', 'MCF7').
expressed_in('MAST1', 'HL60').
expressed_in('MAST1', 'NTERA2').
expressed_in('MAST2', 'MCF7').
expressed_in('MAST2', 'HL60').
expressed_in('MAST2', 'NTERA2').
expressed_in('MAST4', 'MCF7').
expressed_in('MAST4', 'HL60').
expressed_in('MAST4', 'NTERA2').
expressed_in('MELK', 'MCF7').
expressed_in('MELK', 'HL60').
expressed_in('MELK', 'NTERA2').
expressed_in('MARK4', 'HL60').
expressed_in('KIT', 'HL60').
expressed_in('CAMKK1', 'MCF7').
expressed_in('CAMKK1', 'HL60').
expressed_in('KSR1', 'MCF7').
expressed_in('KSR1', 'HL60').
expressed_in('KSR1', 'NTERA2').
expressed_in('PRKCA', 'HL60').
expressed_in('RPS6KA6', 'MCF7').
expressed_in('RPS6KA6', 'HL60').
expressed_in('RPS6KA6', 'NTERA2').
expressed_in('SYK', 'HL60').
expressed_in('PRKACA', 'MCF7').
expressed_in('PRKACA', 'HL60').
expressed_in('PRKACA', 'NTERA2').
expressed_in('CSNK1A1L', 'MCF7').
expressed_in('CSNK1A1L', 'NTERA2').
expressed_in('CSNK1D', 'MCF7').
expressed_in('CSNK1D', 'HL60').
expressed_in('CSNK1D', 'NTERA2').
expressed_in('CSNK1G3', 'HL60').
expressed_in('LCK', 'MCF7').
expressed_in('LCK', 'NTERA2').
expressed_in('RPS6KB1', 'MCF7').
expressed_in('RPS6KB1', 'HL60').
expressed_in('RPS6KB1', 'NTERA2').
expressed_in('RPS6KA4', 'MCF7').
expressed_in('RPS6KA4', 'HL60').
expressed_in('RPS6KA4', 'NTERA2').
expressed_in('LATS2', 'MCF7').
expressed_in('LATS2', 'NTERA2').
expressed_in('PRKCI', 'MCF7').
expressed_in('PRKCI', 'HL60').
expressed_in('PRKCI', 'NTERA2').
expressed_in('PRKCQ', 'MCF7').
expressed_in('PRKCQ', 'HL60').
expressed_in('PRKCQ', 'NTERA2').
expressed_in('PRKCD', 'MCF7').
expressed_in('PRKCD', 'HL60').
expressed_in('PRKCD', 'NTERA2').
expressed_in('GAK', 'MCF7').
expressed_in('GAK', 'HL60').
expressed_in('GAK', 'NTERA2').
expressed_in('HIPK1', 'MCF7').
expressed_in('HIPK1', 'HL60').
expressed_in('HIPK1', 'NTERA2').
expressed_in('HIPK3', 'MCF7').
expressed_in('HIPK3', 'HL60').
expressed_in('MAPK15', 'MCF7').
expressed_in('MAPK15', 'HL60').
expressed_in('MAPK15', 'NTERA2').
expressed_in('MKNK2', 'HL60').
expressed_in('MKNK2', 'NTERA2').
expressed_in('CDC42BPG', 'MCF7').
expressed_in('MAPK9', 'HL60').
expressed_in('CDC42BPB', 'MCF7').
expressed_in('CDC42BPB', 'NTERA2').
expressed_in('MAP2K6', 'MCF7').
expressed_in('MAP2K6', 'HL60').
expressed_in('MAP2K6', 'NTERA2').
expressed_in('MTOR', 'MCF7').
expressed_in('MTOR', 'HL60').
expressed_in('MTOR', 'NTERA2').
expressed_in('MAP2K1', 'MCF7').
expressed_in('MAP2K1', 'HL60').
expressed_in('MAP2K1', 'NTERA2').
expressed_in('MAP2K2', 'MCF7').
expressed_in('MAP2K2', 'HL60').
expressed_in('MAP2K2', 'NTERA2').
expressed_in('CDC42BPA', 'NTERA2').
expressed_in('MAPK3', 'MCF7').
expressed_in('MAPK3', 'HL60').
expressed_in('MAPK3', 'NTERA2').
expressed_in('MAPK6', 'MCF7').
expressed_in('MAPK6', 'NTERA2').
expressed_in('AKT1', 'MCF7').
expressed_in('AKT1', 'HL60').
expressed_in('AKT1', 'NTERA2').
expressed_in('GRK3', 'MCF7').
expressed_in('GRK3', 'HL60').
expressed_in('GRK3', 'NTERA2').
expressed_in('FLT4', 'MCF7').
expressed_in('FLT4', 'HL60').
expressed_in('FLT4', 'NTERA2').
expressed_in('KDR', 'MCF7').
expressed_in('KDR', 'NTERA2').
expressed_in('MASTL', 'MCF7').
expressed_in('MASTL', 'HL60').
expressed_in('MASTL', 'NTERA2').
expressed_in('GSK3A', 'MCF7').
expressed_in('GSK3A', 'HL60').
expressed_in('GSK3A', 'NTERA2').
expressed_in('GSK3B', 'MCF7').
expressed_in('GSK3B', 'HL60').
expressed_in('GSK3B', 'NTERA2').
expressed_in('VRK1', 'MCF7').
expressed_in('VRK1', 'HL60').
expressed_in('VRK1', 'NTERA2').
expressed_in('WNK1', 'MCF7').
expressed_in('WNK1', 'HL60').
expressed_in('WNK1', 'NTERA2').
expressed_in('TYK2', 'MCF7').
expressed_in('TYK2', 'HL60').
expressed_in('TYK2', 'NTERA2').
expressed_in('WNK2', 'MCF7').
expressed_in('WNK2', 'HL60').
expressed_in('WNK2', 'NTERA2').
expressed_in('VRK3', 'MCF7').
expressed_in('VRK3', 'HL60').
expressed_in('VRK3', 'NTERA2').
expressed_in('WNK4', 'MCF7').
expressed_in('WNK4', 'HL60').
expressed_in('WNK4', 'NTERA2').
expressed_in('YES1', 'MCF7').
expressed_in('YES1', 'HL60').
expressed_in('YES1', 'NTERA2').
expressed_in('WEE1', 'MCF7').
expressed_in('WEE1', 'HL60').
expressed_in('WEE1', 'NTERA2').
expressed_in('WNK3', 'MCF7').
expressed_in('WNK3', 'HL60').
expressed_in('WNK3', 'NTERA2').
expressed_in('ULK1', 'MCF7').
expressed_in('ULK1', 'HL60').
expressed_in('ULK1', 'NTERA2').
expressed_in('TRPM7', 'MCF7').
expressed_in('TRPM7', 'HL60').
expressed_in('TTK', 'MCF7').
expressed_in('TTK', 'HL60').
expressed_in('TTK', 'NTERA2').
expressed_in('ULK3', 'MCF7').
expressed_in('ULK3', 'NTERA2').
