kinase('AAK1').
kinase('AATK').
kinase('ABL1').
kinase('ABL2').
kinase('ACVR1').
kinase('ACVR1B').
kinase('ACVR1C').
kinase('ACVR2A').
kinase('ACVR2B').
kinase('ACVRL1').
kinase('ADCK1').
kinase('ADCK2').
kinase('ADCK5').
kinase('AKT1').
kinase('AKT2').
kinase('AKT3').
kinase('ALK').
kinase('ALPK1').
kinase('ALPK2').
kinase('ALPK3').
kinase('AMHR2').
kinase('ANKK1').
kinase('ARAF').
kinase('ATM').
kinase('ATR').
kinase('AURKA').
kinase('AURKB').
kinase('AURKC').
kinase('AXL').
kinase('BARK').
kinase('BAZ1B').
kinase('BCKDK').
kinase('BCR').
kinase('BLK').
kinase('BMP2K').
kinase('BMPR1A').
kinase('BMPR1B').
kinase('BMPR2').
kinase('BMX').
kinase('BRAF').
kinase('BRSK1').
kinase('BRSK2').
kinase('BTK').
kinase('BUB1').
kinase('BUB1B').
kinase('CAMK1').
kinase('CAMK1D').
kinase('CAMK1G').
kinase('CAMK2A').
kinase('CAMK2B').
kinase('CAMK2D').
kinase('CAMK2G').
kinase('CAMK4').
kinase('CAMKK1').
kinase('CAMKK2').
kinase('CAMKV').
kinase('CASK').
kinase('CDC42BPA').
kinase('CDC42BPB').
kinase('CDC42BPG').
kinase('CDC7').
kinase('CDK1').
kinase('CDK10').
kinase('CDK11A').
kinase('CDK11B').
kinase('CDK12').
kinase('CDK13').
kinase('CDK14').
kinase('CDK15').
kinase('CDK16').
kinase('CDK17').
kinase('CDK18').
kinase('CDK19').
kinase('CDK2').
kinase('CDK20').
kinase('CDK3').
kinase('CDK4').
kinase('CDK5').
kinase('CDK6').
kinase('CDK7').
kinase('CDK8').
kinase('CDK9').
kinase('CDKL1').
kinase('CDKL2').
kinase('CDKL3').
kinase('CDKL4').
kinase('CDKL5').
kinase('CHEK1').
kinase('CHEK2').
kinase('CHUK').
kinase('CIITA').
kinase('CILK1').
kinase('CIT').
kinase('CLK1').
kinase('CLK2').
kinase('CLK3').
kinase('CLK4').
kinase('COQ8A').
kinase('COQ8B').
kinase('CSF1R').
kinase('CSK').
kinase('CSNK1A1').
kinase('CSNK1A1L').
kinase('CSNK1D').
kinase('CSNK1E').
kinase('CSNK1G1').
kinase('CSNK1G2').
kinase('CSNK1G3').
kinase('CSNK2A1').
kinase('CSNK2A2').
kinase('CSNK2A3').
kinase('CSNK2B').
kinase('DAPK1').
kinase('DAPK2').
kinase('DAPK3').
kinase('DCAF1').
kinase('DCLK1').
kinase('DCLK2').
kinase('DCLK3').
kinase('DDR1').
kinase('DDR2').
kinase('DMPK').
kinase('DSTYK').
kinase('DYRK1A').
kinase('DYRK1B').
kinase('DYRK2').
kinase('DYRK3').
kinase('DYRK4').
kinase('EEF2K').
kinase('EGFR').
kinase('EIF2AK1').
kinase('EIF2AK2').
kinase('EIF2AK3').
kinase('EIF2AK4').
kinase('EPHA1').
kinase('EPHA10').
kinase('EPHA2').
kinase('EPHA3').
kinase('EPHA4').
kinase('EPHA5').
kinase('EPHA6').
kinase('EPHA7').
kinase('EPHA8').
kinase('EPHB1').
kinase('EPHB2').
kinase('EPHB3').
kinase('EPHB4').
kinase('EPHB6').
kinase('ERBB2').
kinase('ERBB3').
kinase('ERBB4').
kinase('ERN1').
kinase('ERN2').
kinase('FAK2').
kinase('FAM20C').
kinase('FASTK').
kinase('FER').
kinase('FES').
kinase('FGFR1').
kinase('FGFR2').
kinase('FGFR3').
kinase('FGFR4').
kinase('FGR').
kinase('FLT').
kinase('FLT1').
kinase('FLT3').
kinase('FLT4').
kinase('FRK').
kinase('FYN').
kinase('GAK').
kinase('GRK1').
kinase('GRK2').
kinase('GRK3').
kinase('GRK4').
kinase('GRK5').
kinase('GRK6').
kinase('GRK7').
kinase('GSG2').
kinase('GSK3A').
kinase('GSK3B').
kinase('GUCY2C').
kinase('GUCY2D').
kinase('GUCY2F').
kinase('HASPIN').
kinase('HCK').
kinase('HIPK1').
kinase('HIPK2').
kinase('HIPK3').
kinase('HIPK4').
kinase('HUNK').
kinase('IGF1R').
kinase('IKBKB').
kinase('IKBKE').
kinase('ILK').
kinase('INSR').
kinase('INSRR').
kinase('IRAK1').
kinase('IRAK2').
kinase('IRAK3').
kinase('IRAK4').
kinase('ITK').
kinase('JAK1').
kinase('JAK2').
kinase('JAK3').
kinase('KALRN').
kinase('KDR').
kinase('KIT').
kinase('KSR1').
kinase('KSR2').
kinase('LATS1').
kinase('LATS2').
kinase('LCK').
kinase('LIMK1').
kinase('LIMK2').
kinase('LMTK2').
kinase('LMTK3').
kinase('LRRK1').
kinase('LRRK2').
kinase('LTK').
kinase('LYN').
kinase('MAK').
kinase('MAP2K1').
kinase('MAP2K2').
kinase('MAP2K3').
kinase('MAP2K4').
kinase('MAP2K5').
kinase('MAP2K6').
kinase('MAP2K7').
kinase('MAP3K1').
kinase('MAP3K10').
kinase('MAP3K11').
kinase('MAP3K12').
kinase('MAP3K13').
kinase('MAP3K14').
kinase('MAP3K15').
kinase('MAP3K19').
kinase('MAP3K2').
kinase('MAP3K20').
kinase('MAP3K21').
kinase('MAP3K3').
kinase('MAP3K4').
kinase('MAP3K5').
kinase('MAP3K6').
kinase('MAP3K7').
kinase('MAP3K8').
kinase('MAP3K9').
kinase('MAP4K1').
kinase('MAP4K2').
kinase('MAP4K3').
kinase('MAP4K4').
kinase('MAP4K5').
kinase('MAPK1').
kinase('MAPK10').
kinase('MAPK11').
kinase('MAPK12').
kinase('MAPK13').
kinase('MAPK14').
kinase('MAPK15').
kinase('MAPK3').
kinase('MAPK4').
kinase('MAPK6').
kinase('MAPK7').
kinase('MAPK8').
kinase('MAPK9').
kinase('MAPKAPK2').
kinase('MAPKAPK3').
kinase('MAPKAPK5').
kinase('MARK1').
kinase('MARK2').
kinase('MARK3').
kinase('MARK4').
kinase('MAST1').
kinase('MAST2').
kinase('MAST3').
kinase('MAST4').
kinase('MASTL').
kinase('MATK').
kinase('MELK').
kinase('MERTK').
kinase('MET').
kinase('MINK1').
kinase('MKNK1').
kinase('MKNK2').
kinase('MLKL').
kinase('MOK').
kinase('MOS').
kinase('MST1').
kinase('MST1R').
kinase('MTOR').
kinase('MUSK').
kinase('MYLK').
kinase('MYLK2').
kinase('MYLK3').
kinase('MYLK4').
kinase('MYO3A').
kinase('MYO3B').
kinase('NEK1').
kinase('NEK10').
kinase('NEK11').
kinase('NEK2').
kinase('NEK3').
kinase('NEK4').
kinase('NEK5').
kinase('NEK6').
kinase('NEK7').
kinase('NEK8').
kinase('NEK9').
kinase('NIM1K').
kinase('NLK').
kinase('NPR1').
kinase('NPR2').
kinase('NRBP1').
kinase('NRBP2').
kinase('NRK').
kinase('NTRK1').
kinase('NTRK2').
kinase('NTRK3').
kinase('NUAK1').
kinase('NUAK2').
kinase('OBSCN').
kinase('OXSR1').
kinase('PAK1').
kinase('PAK2').
kinase('PAK3').
kinase('PAK4').
kinase('PAK5').
kinase('PAK6').
kinase('PAN3').
kinase('PASK').
kinase('PBK').
kinase('PDGFRA').
kinase('PDGFRB').
kinase('PDIK1L').
kinase('PDK1').
kinase('PDK2').
kinase('PDK3').
kinase('PDK4').
kinase('PDPK1').
kinase('PDPK2P').
kinase('PEAK1').
kinase('PEAK3').
kinase('PHKA1').
kinase('PHKB').
kinase('PHKG1').
kinase('PHKG2').
kinase('PIK3C2A').
kinase('PIK3CA').
kinase('PIK3CB').
kinase('PIK3CD').
kinase('PIK3CG').
kinase('PIK3R4').
kinase('PIM1').
kinase('PIM2').
kinase('PIM3').
kinase('PINK1').
kinase('PKDCC').
kinase('PKMYT1').
kinase('PKN1').
kinase('PKN2').
kinase('PKN3').
kinase('PLK1').
kinase('PLK2').
kinase('PLK3').
kinase('PLK4').
kinase('PLK5').
kinase('PNCK').
kinase('POMK').
kinase('PRAG1').
kinase('PRKAA1').
kinase('PRKAA2').
kinase('PRKAB1').
kinase('PRKACA').
kinase('PRKACB').
kinase('PRKACG').
kinase('PRKCA').
kinase('PRKCB').
kinase('PRKCD').
kinase('PRKCE').
kinase('PRKCG').
kinase('PRKCH').
kinase('PRKCI').
kinase('PRKCQ').
kinase('PRKCZ').
kinase('PRKD1').
kinase('PRKD2').
kinase('PRKD3').
kinase('PRKDC').
kinase('PRKG1').
kinase('PRKG2').
kinase('PRKX').
kinase('PRKY').
kinase('PRPF4B').
kinase('PRPK').
kinase('PSKH1').
kinase('PSKH2').
kinase('PTK2').
kinase('PTK2B').
kinase('PTK6').
kinase('PTK7').
kinase('PXK').
kinase('RAF1').
kinase('RET').
kinase('RIOK1').
kinase('RIOK2').
kinase('RIOK3').
kinase('RIPK1').
kinase('RIPK2').
kinase('RIPK3').
kinase('RIPK4').
kinase('RNASEL').
kinase('ROCK1').
kinase('ROCK2').
kinase('ROR1').
kinase('ROR2').
kinase('ROS1').
kinase('RPS6KA1').
kinase('RPS6KA2').
kinase('RPS6KA3').
kinase('RPS6KA4').
kinase('RPS6KA5').
kinase('RPS6KA6').
kinase('RPS6KB1').
kinase('RPS6KB2').
kinase('RPS6KC1').
kinase('RPS6KL1').
kinase('RSKR').
kinase('RYK').
kinase('SBK1').
kinase('SBK2').
kinase('SBK3').
kinase('SCYL1').
kinase('SCYL2').
kinase('SCYL3').
kinase('SGK1').
kinase('SGK2').
kinase('SGK3').
kinase('SIK1').
kinase('SIK1B').
kinase('SIK2').
kinase('SIK3').
kinase('SLK').
kinase('SMG1').
kinase('SNRK').
kinase('SPEG').
kinase('SRC').
kinase('SRMS').
kinase('SRPK1').
kinase('SRPK2').
kinase('SRPK3').
kinase('STK10').
kinase('STK11').
kinase('STK16').
kinase('STK17A').
kinase('STK17B').
kinase('STK19').
kinase('STK24').
kinase('STK25').
kinase('STK26').
kinase('STK3').
kinase('STK31').
kinase('STK32A').
kinase('STK32B').
kinase('STK32C').
kinase('STK33').
kinase('STK35').
kinase('STK36').
kinase('STK38').
kinase('STK38L').
kinase('STK39').
kinase('STK4').
kinase('STK40').
kinase('STKLD1').
kinase('STRADA').
kinase('STRADB').
kinase('STYK1').
kinase('SYK').
kinase('TAF1').
kinase('TAOK1').
kinase('TAOK2').
kinase('TAOK3').
kinase('TBCK').
kinase('TBK1').
kinase('TEC').
kinase('TEK').
kinase('TESK1').
kinase('TESK2').
kinase('TEX14').
kinase('TGFBR1').
kinase('TGFBR2').
kinase('TIE1').
kinase('TLK1').
kinase('TLK2').
kinase('TNIK').
kinase('TNK1').
kinase('TNK2').
kinase('TNNI3K').
kinase('TP53RK').
kinase('TRIB1').
kinase('TRIB2').
kinase('TRIB3').
kinase('TRIO').
kinase('TRPM6').
kinase('TRPM7').
kinase('TSSK1B').
kinase('TSSK2').
kinase('TSSK3').
kinase('TSSK4').
kinase('TSSK6').
kinase('TTBK1').
kinase('TTBK2').
kinase('TTK').
kinase('TTN').
kinase('TXK').
kinase('TYK2').
kinase('TYRO3').
kinase('UHMK1').
kinase('ULK1').
kinase('ULK2').
kinase('ULK3').
kinase('ULK4').
kinase('VRK1').
kinase('VRK2').
kinase('VRK3').
kinase('WEE1').
kinase('WEE2').
kinase('WNK1').
kinase('WNK2').
kinase('WNK3').
kinase('WNK4').
kinase('YES1').
kinase('ZAP70').
