phosphatase('ACP1').
phosphatase('CDC14A').
phosphatase('CDC14B').
phosphatase('CDC14C').
phosphatase('CDC25A').
phosphatase('CDC25B').
phosphatase('CDC25C').
phosphatase('CDKN3').
phosphatase('CPPED1').
phosphatase('CTDNEP1').
phosphatase('CTDP1').
phosphatase('CTDSP1').
phosphatase('CTDSP2').
phosphatase('CTDSPL').
phosphatase('DNAJC6').
phosphatase('DUPD1').
phosphatase('DUSP1').
phosphatase('DUSP10').
phosphatase('DUSP12').
phosphatase('DUSP13').
phosphatase('DUSP14').
phosphatase('DUSP15').
phosphatase('DUSP16').
phosphatase('DUSP18').
phosphatase('DUSP19').
phosphatase('DUSP2').
phosphatase('DUSP21').
phosphatase('DUSP22').
phosphatase('DUSP23').
phosphatase('DUSP26').
phosphatase('DUSP28').
phosphatase('DUSP3').
phosphatase('DUSP4').
phosphatase('DUSP5').
phosphatase('DUSP6').
phosphatase('DUSP7').
phosphatase('DUSP8').
phosphatase('DUSP9').
phosphatase('EPM2A').
phosphatase('EYA1').
phosphatase('EYA2').
phosphatase('EYA3').
phosphatase('EYA4').
phosphatase('ILKAP').
phosphatase('MDP1').
phosphatase('MTMR3').
phosphatase('MTMR4').
phosphatase('PGAM5').
phosphatase('PGP').
phosphatase('PHLPP1').
phosphatase('PHLPP2').
phosphatase('PPEF1').
phosphatase('PPEF2').
phosphatase('PPM1A').
phosphatase('PPM1B').
phosphatase('PPM1D').
phosphatase('PPM1E').
phosphatase('PPM1F').
phosphatase('PPM1G').
phosphatase('PPM1H').
phosphatase('PPM1J').
phosphatase('PPM1K').
phosphatase('PPM1L').
phosphatase('PPM1M').
phosphatase('PPM1N').
phosphatase('PPP1CA').
phosphatase('PPP1CB').
phosphatase('PPP1CC').
phosphatase('PPP2CA').
phosphatase('PPP2CB').
phosphatase('PPP3CA').
phosphatase('PPP3CB').
phosphatase('PPP3CC').
phosphatase('PPP4C').
phosphatase('PPP5C').
phosphatase('PPP6C').
phosphatase('PPTC7').
phosphatase('PTEN').
phosphatase('PTP4A1').
phosphatase('PTP4A2').
phosphatase('PTP4A3').
phosphatase('PTPMT1').
phosphatase('PTPN1').
phosphatase('PTPN11').
phosphatase('PTPN12').
phosphatase('PTPN13').
phosphatase('PTPN14').
phosphatase('PTPN18').
phosphatase('PTPN2').
phosphatase('PTPN20').
phosphatase('PTPN21').
phosphatase('PTPN22').
phosphatase('PTPN23').
phosphatase('PTPN3').
phosphatase('PTPN4').
phosphatase('PTPN5').
phosphatase('PTPN6').
phosphatase('PTPN7').
phosphatase('PTPN9').
phosphatase('PTPRA').
phosphatase('PTPRB').
phosphatase('PTPRC').
phosphatase('PTPRD').
phosphatase('PTPRE').
phosphatase('PTPRF').
phosphatase('PTPRG').
phosphatase('PTPRH').
phosphatase('PTPRJ').
phosphatase('PTPRK').
phosphatase('PTPRM').
phosphatase('PTPRN2').
phosphatase('PTPRO').
phosphatase('PTPRQ').
phosphatase('PTPRR').
phosphatase('PTPRS').
phosphatase('PTPRT').
phosphatase('PTPRU').
phosphatase('PTPRZ1').
phosphatase('RPAP2').
phosphatase('SSH1').
phosphatase('SSH2').
phosphatase('SSH3').
phosphatase('SSU72').
phosphatase('TNS2').
phosphatase('TPTE').
phosphatase('UBASH3B').
phosphatase('UBLCP1').
